const { test, expect } = require('@playwright/test');
const { PDFDocument, StandardFonts } = require('../vendor/pdf-lib.min.js');
const { pathToFileURL } = require('node:url');
const { readFile } = require('node:fs/promises');
const { resolve } = require('node:path');

test('opens, edits, saves, and protects PDF bytes directly from disk without network', async ({ page, context }) => {
  test.setTimeout(90000);
  await context.setOffline(true);
  const root = process.env.PDFSPLAT_OFFLINE_ROOT || resolve(__dirname, '../../..');
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(pathToFileURL(resolve(root, 'solutions/pdfsplat/index.html')).href);
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  doc.addPage([300, 500]).drawText('Offline original', { x: 30, y: 450, font });
  await page.locator('#fileInput').setInputFiles({name:'offline.pdf',mimeType:'application/pdf',buffer:Buffer.from(await doc.save())});
  await expect(page.locator('#status')).toContainText('1 pages');
  await expect(page.locator('#pdfCanvas')).toBeVisible();
  await page.getByRole('button',{name:'Add text',exact:true}).click();
  await page.locator('#textValue').fill('Saved offline');
  const saved = page.waitForEvent('download');
  await page.locator('#saveAsSelect').selectOption('pdf');
  const copy = await saved;
  expect(await copy.failure()).toBeNull();
  await page.reload();
  await page.locator('#fileInput').setInputFiles({name:copy.suggestedFilename(),mimeType:'application/pdf',buffer:await readFile(await copy.path())});
  await expect(page.locator('#status')).toContainText('1 pages');
  await page.getByRole('button',{name:'Protect / Unprotect'}).click();
  await page.getByRole('button',{name:'Protect this PDF'}).click();
  await page.locator('#vaultPassword').fill('offline-password-test');
  await page.locator('#vaultConfirm').fill('offline-password-test');
  const encrypted = page.waitForEvent('download');
  await page.getByRole('button',{name:'Protect and download'}).click();
  const vault = await encrypted;
  await page.getByRole('button',{name:'Protect / Unprotect'}).click();
  await page.getByRole('button',{name:'Unprotect a PDF'}).click();
  await page.locator('#vaultInput').setInputFiles(await vault.path());
  await page.locator('#vaultPassword').fill('offline-password-test');
  await page.getByRole('button',{name:'Unprotect and open'}).click();
  await expect(page.locator('#status')).toContainText('authenticated, decrypted, and opened locally', {timeout:60000});
  expect(errors).toEqual([]);
});
