const {test,expect}=require('@playwright/test');
const {PDFDocument,rgb,degrees}=require('../vendor/pdf-lib.min.js');
const Zip=require('../../../vendor/jszip.min.js');
const fs=require('fs/promises');
async function open(page,pages=1){const pdf=await PDFDocument.create();for(let i=0;i<pages;i++){const p=pdf.addPage([300,200]);p.drawRectangle({x:0,y:0,width:80,height:40,color:i?rgb(0,0,1):rgb(1,0,0)});if(!i)p.setRotation(degrees(180));}await page.goto('/solutions/pdfsplat/');await page.locator('#fileInput').setInputFiles({name:'images.pdf',mimeType:'application/pdf',buffer:Buffer.from(await pdf.save())});await expect(page.locator('#status')).toContainText(`${pages} pages`);}
async function save(page,format){const pending=page.waitForEvent('download');await page.locator('#saveAsSelect').selectOption(format);const file=await pending;await expect(page.locator('#saveAsSelect')).toBeEnabled();return {name:file.suggestedFilename(),bytes:await fs.readFile(await file.path())};}
async function inspect(page,bytes,mime){return page.evaluate(async({base64,mime})=>{const blob=new Blob([Uint8Array.from(atob(base64),c=>c.charCodeAt(0))],{type:mime}),bitmap=await createImageBitmap(blob),c=document.createElement('canvas');c.width=bitmap.width;c.height=bitmap.height;const ctx=c.getContext('2d');ctx.drawImage(bitmap,0,0);const pixel=[...ctx.getImageData(c.width-10,10,1,1).data];let dark=0;const data=ctx.getImageData(100,100,350,200).data;for(let i=0;i<data.length;i+=4)if(data[i]<100&&data[i+1]<100&&data[i+2]<100)dark++;bitmap.close();return {width:c.width,height:c.height,pixel,dark};},{base64:bytes.toString('base64'),mime});}
for(const [format,mime] of [['png','image/png'],['jpg','image/jpeg'],['webp','image/webp']]){
 test(`${format} Save as exports one image with rotation and edits`,async({page})=>{await open(page);await page.locator('#addTextButton').click();const layer=page.locator('#annotationLayer');await expect(page.locator('.placement-preview')).toBeVisible();const box=await layer.boundingBox();await layer.click({position:{x:box.width*.3,y:box.height*.3}});await page.locator('.inline-text-editor').fill('Added text');await page.locator('.inline-text-editor').press('Tab');const file=await save(page,format);expect(file.name).toBe(`images-page-1.${format}`);const image=await inspect(page,file.bytes,mime);expect([image.width,image.height]).toEqual([600,400]);expect(image.pixel[0]).toBeGreaterThan(245);expect(image.pixel[1]).toBeLessThan(10);expect(image.dark).toBeGreaterThan(20);await expect(page.locator('.text-object')).toHaveCount(1);});
 test(`${format} Save as exports every page in a numbered ZIP`,async({page})=>{await open(page,2);const file=await save(page,format);expect(file.name).toBe('images-images.zip');const zip=await Zip.loadAsync(file.bytes);expect(Object.keys(zip.files)).toEqual([`page-1.${format}`,`page-2.${format}`]);for(const name of Object.keys(zip.files)){const bytes=await zip.file(name).async('nodebuffer');if(format==='png')expect(bytes.subarray(1,4).toString()).toBe('PNG');if(format==='jpg')expect([...bytes.subarray(0,3)]).toEqual([255,216,255]);if(format==='webp'){expect(bytes.subarray(0,4).toString()).toBe('RIFF');expect(bytes.subarray(8,12).toString()).toBe('WEBP');}expect((await inspect(page,bytes,mime)).width).toBe(600);}await expect(page.locator('.thumbnail')).toHaveCount(2);});
}
