import { useMemo, useRef, useState } from "react";
import { estimatedBytes, optimizeVideo, OPTIMIZER_PRESETS, type OptimizeOptions, type OptimizerPreset } from "../optimizer/optimizer";

const bytes = (value: number) => value < 1024 * 1024 ? `${Math.round(value / 1024)} KB` : `${(value / 1024 / 1024).toFixed(1)} MB`;

export function OptimizerDialog({ onClose, onAdd, onStatus }: { onClose: () => void; onAdd: (file: File) => Promise<void>; onStatus: (message: string) => void }) {
  const [file, setFile] = useState<File>(); const [duration, setDuration] = useState(0); const [preset, setPreset] = useState<OptimizerPreset>("editing"); const [custom, setCustom] = useState<OptimizeOptions>(OPTIMIZER_PRESETS.editing); const [progress, setProgress] = useState(0); const [result, setResult] = useState<Blob>(); const [busy, setBusy] = useState(false); const controller = useRef<AbortController | undefined>(undefined);
  const options = preset === "custom" ? custom : OPTIMIZER_PRESETS[preset]; const estimate = useMemo(() => duration ? estimatedBytes(duration, options) : 0, [duration, options]);
  const choose = async (next?: File) => { if (!next) return; setFile(next); setResult(undefined); const url = URL.createObjectURL(next); const video = document.createElement("video"); video.preload="metadata"; video.src=url; await new Promise<void>((resolve) => { video.onloadedmetadata=()=>resolve(); video.onerror=()=>resolve(); }); setDuration(Number.isFinite(video.duration)?video.duration:0); video.removeAttribute("src"); video.load(); URL.revokeObjectURL(url); };
  const run = async () => { if (!file) return; setBusy(true); setProgress(0); controller.current = new AbortController(); try { const output = await optimizeVideo(file, options, setProgress, controller.current.signal); setResult(output); onStatus(`Optimized locally: ${bytes(file.size)} → ${bytes(output.size)}`); } catch (error) { onStatus(error instanceof Error ? error.message : "Optimization failed"); } finally { setBusy(false); } };
  const outputFile = () => new File(result ? [result] : [], `${file?.name.replace(/\.[^.]+$/,"") || "video"}-optimized.webm`, { type: result?.type || "video/webm" });
  const download = () => { const url=URL.createObjectURL(result!); const link=document.createElement("a"); link.href=url; link.download=outputFile().name; link.click(); setTimeout(()=>URL.revokeObjectURL(url),0); };
  return <><button className="dialog-close" onClick={onClose} aria-label="Close">×</button><h2 id="optimizer-title">Optimize video locally</h2><p className="lead">Create a smaller working or sharing copy without uploading or changing the original. Encoding runs in real time while this dialog remains open.</p><label className="file-drop">Source video<input type="file" accept="video/*" onChange={(event)=>choose(event.target.files?.[0])}/><span>{file ? `${file.name} · ${bytes(file.size)}${duration?` · ${duration.toFixed(1)}s`:""}` : "Choose a video"}</span></label><label>Preset<select value={preset} onChange={(event)=>setPreset(event.target.value as OptimizerPreset)}><option value="editing">Editing proxy · 720p</option><option value="share">Smaller share copy · 1080p</option><option value="tiny">Tiny review copy · 480p</option><option value="custom">Custom</option></select></label>{preset === "custom" && <div className="optimizer-grid"><label>Max width<input type="number" value={custom.maxWidth} onChange={(event)=>setCustom({...custom,maxWidth:Number(event.target.value)})}/></label><label>Max height<input type="number" value={custom.maxHeight} onChange={(event)=>setCustom({...custom,maxHeight:Number(event.target.value)})}/></label><label>Video Mbps<input type="number" step=".1" value={custom.videoBitsPerSecond/1e6} onChange={(event)=>setCustom({...custom,videoBitsPerSecond:Number(event.target.value)*1e6})}/></label><label>Frame rate<input type="number" value={custom.frameRate} onChange={(event)=>setCustom({...custom,frameRate:Number(event.target.value)})}/></label></div>}<div className="optimizer-summary"><span>Estimated output</span><strong>{estimate ? `about ${bytes(estimate)}` : "Select a source"}</strong><small>Actual size depends on the browser encoder and footage.</small></div>{busy && <><progress max="1" value={progress}/><button className="danger wide" onClick={()=>controller.current?.abort()}>Cancel optimization</button></>}{!busy && !result && <button className="primary wide" disabled={!file} onClick={run}>Create optimized copy</button>}{result && <div className="optimizer-results"><strong>Optimized copy ready · {bytes(result.size)}</strong><button className="primary" onClick={download}>Download copy</button><button onClick={async()=>{await onAdd(outputFile());onClose();}}>Add to project</button><button onClick={run}>Run again</button></div>}</>;
}
