const {test,expect}=require('@playwright/test');
for(const slug of ['typing-games','road-rally','block-zap','passage-coach','paws-and-keys']){
 test(`${slug}: assets, six languages and responsive layout`,async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
  await page.goto(`/games/${slug}/`);await expect(page.locator('h1')).toBeVisible();await expect(page.locator('[data-i18n-picker] select option')).toHaveCount(6);
  for(const code of ['es','vi','ar','zh','uh','en']){await page.locator('[data-i18n-picker] select').selectOption(code);await expect(page.locator('h1')).not.toBeEmpty()}
  expect(await page.locator('img').evaluateAll(imgs=>imgs.every(i=>i.complete&&i.naturalWidth>0))).toBeTruthy();
  for(const width of [390,1440]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:`/tmp/typing-${slug}-${width}.png`,fullPage:true})}expect(errors).toEqual([]);
 });
}
test('menu links to four separate experiences',async({page})=>{await page.goto('/games/typing-games/');await expect(page.locator('canvas')).toHaveCount(0);await expect(page.locator('.game-card')).toHaveCount(4)});
test('Cipher Chase typing, controls, pause and reset',async({page})=>{
 await page.goto('/games/road-rally/');await page.locator('#start').click();await expect(page.locator('#overlay')).toBeHidden();await page.locator('#word').fill('wrongword');await page.locator('#word').press('Enter');await expect(page.locator('#feedback')).toContainText('No match');await expect(page.locator('#word')).toHaveValue('wrongword');await expect(page.locator('#targets')).not.toBeEmpty();const target=await page.locator('#targets').textContent();await page.locator('#word').fill(target.split(' · ')[0]);await page.locator('#word').press('Enter');await expect(page.locator('#feedback')).toHaveText('Target cleared!');await page.locator('#word').press('ArrowRight');await page.locator('[data-action=smoke]').click();await page.locator('#pause').click();await expect(page.locator('#overlayTitle')).toHaveText('Paused');const score=await page.locator('#score').textContent();await page.waitForTimeout(200);await expect(page.locator('#score')).toHaveText(score);await page.locator('#pause').click();await expect(page.locator('#overlay')).toBeHidden();await page.locator('#reset').click();await expect(page.locator('#lives')).toHaveText('5');
});
test('Wordfall Reactor letters type words and settled words zap',async({page})=>{
 await page.goto('/games/block-zap/');await page.locator('#start').click();await page.locator('#word').press('c');await page.locator('#word').press('x');await expect(page.locator('#word')).toHaveValue('cx');await page.locator('#word').fill('');await page.locator('#word').press('ArrowUp');await page.locator('#word').press('Shift');await page.locator('#word').press('Space');await expect(page.locator('#targets span').first()).toBeVisible();const word=await page.locator('#targets span').first().textContent();await page.locator('#word').fill(word);await page.locator('#word').press('Enter');await expect(page.locator('#feedback')).toHaveText('Target cleared!');expect(Number(await page.locator('#score').textContent())).toBeGreaterThan(100);
});
test('Story Sprint correction, pause, exact completion and deliberate next',async({page})=>{
 await page.goto('/games/passage-coach/');await page.locator('summary').click();await page.locator('#custom').fill('A cat.');await page.locator('#load').click();await page.locator('#practice').fill('A dog.');await expect(page.locator('#errors')).not.toHaveText('0');await page.locator('#pause').click();await expect(page.locator('#practice')).toBeDisabled();await page.locator('#pause').click();await page.locator('#practice').fill('A cat.');await expect(page.locator('#progress')).toHaveText('100%');await expect(page.locator('#accuracy')).toHaveText('100%');await expect(page.locator('#feedback')).toContainText('Passage complete');await page.waitForTimeout(1100);await expect(page.locator('#practice')).toHaveValue('A cat.');await page.locator('#next').click();await expect(page.locator('#practice')).toHaveValue('');
 await page.locator('#file').setInputFiles({name:'passages.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify([{title:'Custom story',text:'<b>Hello</b>'}]))});await expect(page.locator('#passageTitle')).toHaveText('Custom story');await expect(page.locator('#passage b')).toHaveCount(0);await expect(page.locator('#passage')).toHaveText('<b>Hello</b>');await page.locator('#file').setInputFiles({name:'passages.csv',mimeType:'text/csv',buffer:Buffer.from('title,text\nTest,"A cat, a dog."')});await expect(page.locator('#passage')).toHaveText('A cat, a dog.');
});
test('Paws & Keys gentle mistake, unlock, persistence, pet and age',async({page})=>{
 await page.goto('/games/paws-and-keys/');await expect(page.locator('#trailSelect option').nth(1)).toHaveAttribute('disabled','');await page.locator('#keyboard [data-key=a]').click();await expect(page.locator('#pawsFeedback')).toContainText('Try the glowing key');await expect(page.locator('#trailProgress')).toHaveAttribute('value','0');for(let i=0;i<8;i++){const key=await page.locator('#keyboard .glow').getAttribute('data-key');await page.locator(`#keyboard [data-key="${key}"]`).click()}await expect(page.locator('#celebration')).toBeVisible();await expect(page.locator('#trailSelect option').nth(1)).not.toHaveAttribute('disabled','');await page.locator('#nextTrail').click();await expect(page.locator('#trailLabel')).toContainText('Trail 2');await page.locator('#pet').selectOption('puppy');await expect(page.locator('#petRunner')).toHaveAttribute('src',/puppy/);await page.reload();await expect(page.locator('#trailSelect option').nth(1)).not.toHaveAttribute('disabled','');await page.locator('#age').selectOption('big');await expect(page.locator('#trailSelect option').nth(1)).toHaveAttribute('disabled','');await page.locator('#pawsPause').click();await expect(page.locator('#keyboard [data-key=f]')).toBeDisabled();await page.locator('#pawsPause').click();await expect(page.locator('#keyboard [data-key=f]')).toBeEnabled();
});
test('Paws & Keys all twelve trails, real keyboard, stars and four worlds',async({page})=>{
 test.setTimeout(60000);await page.goto('/games/paws-and-keys/');
 for(let trail=0;trail<12;trail++){
  await expect(page.locator('.pet-landscape')).toHaveAttribute('src',`../typing-games/assets/world-${Math.floor(trail/3)+1}.webp`);
  for(let i=0;i<8;i++){const word=await page.locator('#keyPrompt').textContent();await page.keyboard.type(word.toLowerCase())}
  await expect(page.locator('#celebration')).toBeVisible();await expect(page.locator('#earnedStars')).toHaveText('★★★');if(trail<11)await page.locator('#nextTrail').click();
 }
 await expect(page.locator('#nextTrail')).toBeDisabled();await expect(page.locator('#starCount')).toHaveText('★ 36');await page.reload();await expect(page.locator('#trailSelect option').last()).not.toHaveAttribute('disabled','');
});
test('Story Sprint XLSX inline strings and sparse columns',async({page})=>{
 const JSZip=require('../vendor/jszip.min.js');const zip=new JSZip();zip.file('xl/worksheets/sheet1.xml','<worksheet><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>title</t></is></c><c r="B1" t="inlineStr"><is><t>text</t></is></c></row><row r="2"><c r="A2" t="inlineStr"><is><t>A spreadsheet story</t></is></c><c r="B2" t="inlineStr"><is><t>A puppy naps.</t></is></c></row></sheetData></worksheet>');
 await page.goto('/games/passage-coach/');await page.locator('summary').click();await page.locator('#file').setInputFiles({name:'stories.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:await zip.generateAsync({type:'nodebuffer'})});await expect(page.locator('#passageTitle')).toHaveText('A spreadsheet story');await expect(page.locator('#passage')).toHaveText('A puppy naps.');
});
