const {test,expect}=require('@playwright/test');
const board=(tools=['select','pen','text','audio','video'])=>({title:'Response lesson',mode:'teacher',active:0,studentWorkspace:{view:'beginner',tools},panels:[{id:'p1',name:'My science answer',bg:'blank',objects:[]},{id:'p2',name:'My math answer',bg:'blank',objects:[]}]});
const saved=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('drawsplat.autosave')));
test.beforeEach(async({page})=>{await page.addInitScript(()=>{localStorage.setItem('drawsplat.welcomed','1');localStorage.setItem('drawsplat.consent.accepted','1');localStorage.setItem('drawsplat.startupTipDate',new Date().toISOString().slice(0,10))});await page.goto('/app/whiteboard.html')});
async function load(page,b){await page.locator('#jsonInput').setInputFiles({name:'response.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(b))});await expect(page.locator('#statusToast')).toContainText('Board loaded');await page.goto('/app/whiteboard.html?role=student')}
async function voice(page){await page.evaluate(()=>{Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:async()=>({getTracks:()=>[{stop(){}}]})}});window.MediaRecorder=class{constructor(){this.state='inactive';this.mimeType='audio/webm'}start(){this.state='recording'}stop(){this.state='inactive';this.ondataavailable?.({data:new Blob(['answer'])});this.onstop?.()}}});await page.locator('#learnerResponse').click();await page.locator('#learnerVoiceResponse').click();await page.locator('#learnerRecordAudio').click();await page.locator('#learnerRecordAudio').click();await expect(page.locator('#learnerAddAudio')).toBeEnabled()}
test('illustrated response choices explain each method and fit a phone',async({page})=>{await page.setViewportSize({width:390,height:844});await load(page,board());await page.locator('#learnerResponse').click();const cards=page.locator('.response-choice-card');await expect(cards).toHaveCount(4);for(const card of await cards.all()){await expect(card.locator('strong')).not.toBeEmpty();await expect(card.locator('small')).not.toBeEmpty();const box=await card.boundingBox();expect(box.height).toBeGreaterThanOrEqual(80);expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(390);expect(box.y+box.height).toBeLessThanOrEqual(844)}await page.locator('#learnerTypeResponse').click();await expect(page.locator('#learnerResponseDialog')).not.toBeVisible();await expect(page.locator('#learnerPrimaryTools [data-learner-tool=text]')).toHaveAttribute('aria-pressed','true')});
test('response choices respect the lesson and explain when none are enabled',async({page})=>{await load(page,board(['select','pen']));await page.locator('#learnerResponse').click();await expect(page.locator('#learnerDrawResponse')).toBeVisible();for(const id of ['learnerTypeResponse','learnerVoiceResponse','learnerVideoResponse'])await expect(page.locator('#'+id)).toBeHidden();await page.locator('#learnerResponseDialog .close').click();await page.goto('/app/whiteboard.html?role=student&tools=select');await page.locator('#learnerResponse').click();await expect(page.locator('#learnerResponseEmpty')).toBeVisible();await expect(page.locator('.response-choice-card:visible')).toHaveCount(0)});
test('named voice answers display safe text and retain their names after reload',async({page})=>{await load(page,board());await voice(page);await page.locator('#learnerAudioDetails summary').click();await page.locator('#learnerAudioName').fill('Water <cycle> & clouds');await page.locator('#learnerAddAudio').click();await expect(page.locator('.audio-note-title')).toHaveText('Water <cycle> & clouds');expect((await saved(page)).panels[0].objects[0].audioName).toBe('Water <cycle> & clouds');await page.reload();await expect(page.locator('.audio-note-title')).toHaveText('Water <cycle> & clouds');await expect(page.locator('.audio-note-title cycle')).toHaveCount(0)});
test('unfinished voice answers return to their original page before adding',async({page})=>{await load(page,board());await voice(page);await page.locator('#learnerAudioDialog .close').click();await page.locator('#frameNavNext').click();await page.locator('#learnerFinishVoice').click();await expect(page.locator('#learnerAddAudio')).toBeDisabled();await expect(page.locator('#learnerAudioReturnPage')).toBeVisible();await page.locator('#learnerAudioReturnPage').click();await expect(page.locator('#learnerAddAudio')).toBeEnabled();await page.locator('#learnerAddAudio').click();const b=await saved(page);expect(b.active).toBe(0);expect(b.panels[0].objects).toHaveLength(1);expect(b.panels[1].objects).toHaveLength(0);await page.locator('#learnerUndo').click();expect((await saved(page)).panels[0].objects).toHaveLength(0)});
