const {test,expect}=require('@playwright/test');
const fs=require('node:fs/promises');const vm=require('node:vm');
const clip=require('node:fs').readFileSync('tests/fixtures/video-note.mp4');
const poster='data:image/jpeg;base64,'+require('node:fs').readFileSync('tests/fixtures/video-note-poster.jpg').toString('base64');
const src='data:video/mp4;base64,'+clip.toString('base64');
const fixture=(tools=['select','image'],objects=[])=>({title:'Video lesson',mode:'teacher',assignmentMode:true,active:0,studentWorkspace:{view:'simple',tools},panels:[{id:'p1',name:'My page',bg:'blank',objects}]});
const note={id:'v1',type:'video',x:20,y:30,w:240,h:280,layer:'teacher',videoSrc:src,videoPoster:poster,videoDuration:2,videoName:'Water demonstration',videoCaption:'Watch how water moves.',opacity:1};
const saved=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('drawsplat.autosave')));
async function load(page,b){await page.locator('#jsonInput').setInputFiles({name:'video.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(b))});await expect(page.locator('#statusToast')).toContainText('Board loaded')}
async function mockCamera(page,{denied=false,late=false}={}){
 await page.addInitScript(({base64,denied,late})=>{
  window.cameraRequests=[];window.stoppedTracks=0;
  const stream=()=>{const s=new MediaStream();s.getTracks=()=>[{stop:()=>window.stoppedTracks++},{stop:()=>window.stoppedTracks++}];return s};
  Object.defineProperty(Object.getPrototypeOf(navigator.mediaDevices),'getUserMedia',{configurable:true,value:async constraints=>{window.cameraRequests.push(constraints);if(denied)throw new DOMException('Denied','NotAllowedError');if(late)return new Promise(resolve=>window.grantCamera=()=>resolve(stream()));return stream()}});
  const nativePlay=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){return this.id==='videoNotePreview'&&this.srcObject?Promise.resolve():nativePlay.call(this)};
  class Recorder{constructor(s){this.state='inactive';this.mimeType='video/mp4';this.stream=s}static isTypeSupported(){return true}start(){this.state='recording'}stop(){if(this.state==='inactive')return;this.state='inactive';queueMicrotask(()=>{const raw=Uint8Array.from(atob(base64),c=>c.charCodeAt(0));this.ondataavailable?.({data:new Blob([raw],{type:'video/mp4'})});this.onstop?.()})}}
  window.MediaRecorder=Recorder;
 },{base64:clip.toString('base64'),denied,late});
}
test.beforeEach(async({page})=>{await page.addInitScript(()=>{localStorage.setItem('drawsplat.welcomed','1');localStorage.setItem('drawsplat.consent.accepted','1');localStorage.setItem('drawsplat.startupTipDate',new Date().toISOString().slice(0,10))})});
async function open(page){await page.goto('/app/whiteboard.html');await expect(page.locator('#learnerToolbar')).toBeVisible()}
test('teachers enable student video notes explicitly and share that lesson choice',async({page})=>{
 await open(page);await load(page,fixture());await page.locator('#optionsBtn').evaluate(e=>e.click());await page.locator('.learner-teaching > summary').click();const choice=page.locator('#learnerToolChoices input[value="video"]');await expect(choice).not.toBeChecked();await choice.check();await page.locator('#learnerSaveTools').click();expect((await saved(page)).studentWorkspace.tools).toContain('video');await page.locator('#closeOptions').click();
 await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async s=>window.videoStudentLink=s}});document.querySelector('#collabRoom').value='video-test'});await page.locator('#createStudentLinkBtn').evaluate(e=>e.click());const link=await page.evaluate(()=>window.videoStudentLink);expect(new URL(link).searchParams.get('tools').split(',')).toContain('video');await page.goto(link);await expect(page.locator('#learnerVideoNote')).toBeVisible();
});
test('student recording is off by default while teacher videos remain playable and protected',async({page})=>{
 await mockCamera(page);await open(page);await load(page,fixture(['select','image'],[note]));await page.goto('/app/whiteboard.html?role=student');await expect(page.locator('#learnerVideoNote')).toBeHidden();await page.locator('#learnerVideoNote').evaluate(e=>e.click());await expect(page.locator('#videoNoteDialog')).toBeHidden();expect(await page.evaluate(()=>window.cameraRequests.length)).toBe(0);
 const card=page.locator('.video-note-card');await expect(card.getByRole('button',{name:'Play',exact:true})).toBeVisible();await card.getByRole('button',{name:'Play',exact:true}).click();await expect.poll(()=>card.locator('video').evaluate(e=>!e.paused)).toBe(true);await card.getByRole('button',{name:'Stop',exact:true}).click();await expect.poll(()=>card.locator('video').evaluate(e=>e.currentTime)).toBe(0);await card.locator('strong').click();await page.keyboard.press('Delete');expect((await saved(page)).panels[0].objects.find(o=>o.id==='v1').videoSrc).toBe(src);
});
test('record review retake and add do not leave empty notes or running camera tracks',async({page})=>{
 await mockCamera(page);await open(page);await page.locator('#learnerVideoNote').click();expect(await page.evaluate(()=>window.cameraRequests.length)).toBe(0);await page.locator('#videoNoteMic').uncheck();await page.locator('#videoNoteRecord').click();await expect(page.locator('#videoNoteStatus')).toContainText('Recording…');await expect(page.locator('#videoNoteAdd')).toBeDisabled();await page.locator('#videoNoteStop').click();await expect(page.locator('#videoNoteAdd')).toBeEnabled();expect(await page.evaluate(()=>window.stoppedTracks)).toBe(2);expect(await page.evaluate(()=>window.cameraRequests[0].audio)).toBe(false);await expect(page.locator('#boardSvg .video-note-card')).toHaveCount(0);
 await page.locator('#videoNoteRetake').click();await expect(page.locator('#videoNoteAdd')).toBeDisabled();await page.locator('#videoNoteRecord').click();await expect(page.locator('#videoNoteStop')).toBeEnabled();await page.locator('#videoNoteStop').click();await expect(page.locator('#videoNoteAdd')).toBeEnabled();await page.locator('#videoNoteName').fill('My video answer');await page.locator('#videoNoteCaption').fill('Here is my explanation.');await page.locator('#videoNoteAdd').click();const o=(await saved(page)).panels[0].objects.at(-1);expect(o.type).toBe('video');expect(o.videoName).toBe('My video answer');expect(o.videoCaption).toBe('Here is my explanation.');expect(o.videoSrc).toMatch(/^data:video\/mp4/);expect(await page.evaluate(()=>window.stoppedTracks)).toBe(4);await page.locator('#learnerUndo').click();await expect(page.locator('.video-note-card')).toHaveCount(0);
});
test('recording stops at 30 seconds and camera requests completed after closing are released',async({page})=>{
 await mockCamera(page);await open(page);await page.clock.install();await page.locator('#learnerVideoNote').click();await page.locator('#videoNoteRecord').click();await expect(page.locator('#videoNoteStop')).toBeEnabled();await page.clock.fastForward(31000);await expect(page.locator('#videoNoteAdd')).toBeEnabled();expect(await page.evaluate(()=>window.stoppedTracks)).toBe(2);await page.locator('#videoNoteAdd').click();expect((await saved(page)).panels[0].objects.at(-1).videoDuration).toBe(30);
});
test('closing during camera permission waits cleans up a late camera grant',async({page})=>{
 await mockCamera(page,{late:true});await open(page);await page.locator('#learnerVideoNote').click();await page.locator('#videoNoteRecord').click();await expect(page.locator('#videoNoteStatus')).toContainText('Opening');await page.locator('#videoNoteClose').click();await page.evaluate(()=>window.grantCamera());await expect.poll(()=>page.evaluate(()=>window.stoppedTracks)).toBe(2);await expect(page.locator('.video-note-card')).toHaveCount(0);
});
test('camera errors are explained and closing an active clip releases tracks and keeps review',async({page})=>{
 await mockCamera(page);await open(page);await page.locator('#learnerVideoNote').click();await page.locator('#videoNoteRecord').click();await expect(page.locator('#videoNoteStop')).toBeEnabled();await page.locator('#videoNoteClose').click();await expect.poll(()=>page.evaluate(()=>window.stoppedTracks)).toBe(2);await page.locator('#learnerVideoNote').click();await expect(page.locator('#videoNoteAdd')).toBeEnabled();await expect(page.locator('.video-note-card')).toHaveCount(0);
});
test('camera permission denial is visible without adding a note',async({page})=>{
 await mockCamera(page,{denied:true});await open(page);await page.locator('#learnerVideoNote').click();await page.locator('#videoNoteRecord').click();await expect(page.locator('#videoNoteStatus')).toContainText('not allowed');await expect(page.locator('#videoNoteRecord')).toBeEnabled();await expect(page.locator('#videoNoteAdd')).toBeDisabled();await expect(page.locator('.video-note-card')).toHaveCount(0);
});
for(const width of [390,1280])test('video controls save reload and export a still picture at '+width+'px',async({page})=>{
 await page.setViewportSize({width,height:900});await open(page);const responsive={...note,w:Math.min(240,width-120)};await load(page,fixture(['select'],[responsive]));const card=page.locator('.video-note-card'),video=card.locator('video');await expect.poll(()=>video.evaluate(e=>e.readyState)).toBeGreaterThan(0);await card.getByRole('button',{name:'Play',exact:true}).click();await expect.poll(()=>video.evaluate(e=>!e.paused)).toBe(true);await card.getByRole('button',{name:'Pause',exact:true}).click();await expect.poll(()=>video.evaluate(e=>e.paused)).toBe(true);await card.getByRole('button',{name:'Stop',exact:true}).click();expect(await video.evaluate(e=>e.currentTime)).toBe(0);const before=await saved(page);await page.locator('#sidebarAudioToggleBtn').click();expect(await video.evaluate(e=>e.muted)).toBe(false);expect((await saved(page)).panels).toEqual(before.panels);
 const bounds=await card.boundingBox();expect(bounds.x+bounds.width).toBeLessThanOrEqual(width);const download=page.waitForEvent('download');await page.locator('#exportBtn').evaluate(e=>e.click());const bytes=await fs.readFile(await (await download).path());const blue=await page.evaluate(async data=>{const image=new Image;image.src='data:image/png;base64,'+data;await image.decode();const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const ctx=c.getContext('2d');ctx.drawImage(image,0,0);const pixels=ctx.getImageData(0,0,c.width,c.height).data;let count=0;for(let i=0;i<pixels.length;i+=4)if(pixels[i]<100&&pixels[i+1]<140&&pixels[i+2]>170)count++;return count},bytes.toString('base64'));expect(blue).toBeGreaterThan(1000);await page.reload();await expect(page.locator('.video-note-card strong')).toHaveText('Water demonstration');expect((await saved(page)).panels[0].objects[0].videoSrc).toBe(src);
});
test('Google room merge uses the teacher video policy and preserves existing clips when disabled',()=>{
 const context=vm.createContext({PropertiesService:{getScriptProperties:()=>({})}});vm.runInContext(require('node:fs').readFileSync('apps-script/Code.gs','utf8'),context);context.base=fixture(['select'],[{...note,layer:'student'}]);context.incoming=fixture(['select','video'],[{...note,layer:'student',videoSrc:src+'changed'},{...note,id:'new',layer:'student'}]);let merged=vm.runInContext('mergeStudentBoard_(base,incoming)',context);expect(merged.panels[0].objects).toHaveLength(1);expect(merged.panels[0].objects[0].videoSrc).toBe(src);context.base.studentWorkspace.tools.push('video');merged=vm.runInContext('mergeStudentBoard_(base,incoming)',context);expect(merged.panels[0].objects).toHaveLength(2);
});
test('playback survives canvas redraw and stops when its page is hidden',async({page})=>{
 await open(page);await load(page,fixture(['select'],[note]));const video=page.locator('.video-note-card video');await expect.poll(()=>video.evaluate(e=>e.readyState)).toBeGreaterThan(0);await video.evaluate(e=>{window.originalNotePlayer=e;e.play()});await page.locator('#learnerHome').click();expect(await video.evaluate(e=>e===window.originalNotePlayer)).toBe(true);await expect.poll(()=>video.evaluate(e=>!e.paused)).toBe(true);await video.evaluate(e=>e.pause());await page.locator('#learnerHome').click();expect(await video.evaluate(e=>e.paused)).toBe(true);await page.locator('#frameNavAdd').click();await expect(page.locator('.video-note-card')).toHaveCount(0);expect(await page.evaluate(()=>window.originalNotePlayer.paused)).toBe(true);expect(await page.evaluate(()=>window.originalNotePlayer.getAttribute('src'))).toBe(null);
});
for(const voice of [false,true])test('native recording creates playable video or explains browser limitations — voice '+voice,async({page})=>{
 await page.addInitScript(()=>{Object.defineProperty(Object.getPrototypeOf(navigator.mediaDevices),'getUserMedia',{configurable:true,value:async constraints=>{const canvas=document.createElement('canvas');canvas.width=160;canvas.height=120;const ctx=canvas.getContext('2d');const stream=canvas.captureStream(15);window.nativeCameraStream=stream;if(constraints.audio){const audio=new AudioContext();const oscillator=audio.createOscillator(),gain=audio.createGain(),destination=audio.createMediaStreamDestination();gain.gain.value=.001;oscillator.connect(gain).connect(destination);oscillator.start();stream.addTrack(destination.stream.getAudioTracks()[0]);window.nativeCameraAudioContext=audio;await audio.resume()}let frame=0;const paint=()=>{ctx.fillStyle='#2855f9';ctx.fillRect(0,0,160,120);ctx.fillStyle='white';ctx.fillRect(frame++%120,10,20,20);if(stream.getTracks().some(t=>t.readyState==='live'))requestAnimationFrame(paint)};paint();return stream}})});
 await open(page);await page.locator('#learnerVideoNote').click();if(!await page.evaluate(()=>!!window.MediaRecorder)){await page.locator('#videoNoteRecord').click();await expect(page.locator('#videoNoteStatus')).toContainText('cannot record video');await expect(page.locator('#videoNoteAdd')).toBeDisabled();return}await page.locator('#videoNoteMic').setChecked(voice);await page.locator('#videoNoteRecord').click();await expect(page.locator('#videoNoteStatus')).toContainText('Recording…');await page.waitForTimeout(1200);await page.locator('#videoNoteStop').click();await expect(page.locator('#videoNoteAdd')).toBeEnabled();await page.locator('#videoNoteAdd').click();const o=(await saved(page)).panels[0].objects.at(-1);expect(o.videoPoster).toMatch(/^data:image\/jpeg;base64,/);expect(o.videoSrc.length).toBeGreaterThan(500);expect(await page.evaluate(()=>window.nativeCameraStream.getTracks().every(t=>t.readyState==='ended'))).toBe(true);const video=page.locator('.video-note-card video');await expect.poll(()=>video.evaluate(e=>e.readyState)).toBeGreaterThan(0);await page.locator('.video-note-card').getByRole('button',{name:'Play',exact:true}).click();await expect.poll(()=>video.evaluate(e=>!e.paused)).toBe(true);
});
