const {test,expect}=require('@playwright/test');
const clip=require('node:fs').readFileSync('tests/fixtures/video-note.mp4').toString('base64');
const wav=Buffer.alloc(64044);wav.write('RIFF');wav.writeUInt32LE(64036,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(16000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(64000,40);for(let i=0;i<32000;i++)wav.writeInt16LE(Math.sin(i*2*Math.PI*220/8000)*1000,44+i*2);
const source='data:audio/wav;base64,'+wav.toString('base64');
const fixture=()=>({title:'Recovery lesson',mode:'teacher',studentWorkspace:{view:'simple',tools:['select','audio','video']},active:0,panels:[{id:'p1',name:'Science',bg:'blank',objects:[]},{id:'p2',name:'Math',bg:'blank',objects:[]}]});
const saved=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('drawsplat.autosave')));
test.beforeEach(async({page})=>{await page.addInitScript(({clip,wav})=>{
localStorage.setItem('drawsplat.welcomed','1');localStorage.setItem('drawsplat.consent.accepted','1');localStorage.setItem('drawsplat.startupTipDate',new Date().toISOString().slice(0,10));window.requests=[];
Object.defineProperty(Object.getPrototypeOf(navigator.mediaDevices),'getUserMedia',{configurable:true,value:async constraints=>{window.requests.push(constraints);const stream=new MediaStream();stream.kind=constraints.video?'video':'voice';stream.getTracks=()=>[{stop(){}}];return stream}});
const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){return this.id==='videoNotePreview'&&this.srcObject?Promise.resolve():play.call(this)};
window.MediaRecorder=class{constructor(stream){this.stream=stream;this.state='inactive';this.mimeType=stream.kind==='video'?'video/mp4':'audio/wav'}static isTypeSupported(type){return type==='video/mp4'}start(){this.state='recording'}stop(){this.state='inactive';queueMicrotask(()=>{const bytes=Uint8Array.from(atob(this.stream.kind==='video'?clip:wav),c=>c.charCodeAt(0));this.ondataavailable?.({data:new Blob([bytes],{type:this.mimeType})});this.onstop?.()})}};
},{clip,wav:wav.toString('base64')});await page.goto('/app/whiteboard.html');await page.locator('#jsonInput').setInputFiles({name:'lesson.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture()))});await expect(page.locator('#statusToast')).toContainText('Board loaded')});
async function record(page,kind){if(kind==='voice'){await page.locator('#learnerResponse').click();await page.locator('#learnerVoiceResponse').click();await page.locator('#learnerRecordAudio').click();await page.locator('#learnerRecordAudio').click();await expect(page.locator('#learnerAudioDraftStatus')).toContainText('kept on this device')}else{await page.locator('#learnerVideoNote').click();await page.locator('#videoNoteRecord').click();await expect(page.locator('#videoNoteStatus')).toContainText('Recording…');await page.locator('#videoNoteStop').click();await expect(page.locator('#videoNoteDraftStatus')).toContainText('kept on this device')}}
for(const kind of ['voice','video'])test(`${kind} draft recovers after refresh and is cleared after adding`,async({page})=>{
await record(page,kind);const voice=kind==='voice';await page.locator(voice?'#learnerAudioDetails summary':'#videoNoteDetails summary').click();await page.locator(voice?'#learnerAudioName':'#videoNoteName').fill('My recovered answer');await expect(page.locator(voice?'#learnerAudioDraftStatus':'#videoNoteDraftStatus')).toContainText('kept on this device');await page.reload();expect(await page.evaluate(()=>window.requests)).toHaveLength(0);await page.locator(voice?'#learnerFinishVoice':'#learnerVideoNote').click();await expect(page.locator(voice?'#learnerAudioName':'#videoNoteName')).toHaveValue('My recovered answer');await expect(page.locator(voice?'#learnerAudioDraftStatus':'#videoNoteDraftStatus')).toContainText('Recovered');await page.locator(voice?'#learnerAddAudio':'#videoNoteAdd').click();expect((await saved(page)).panels[0].objects).toHaveLength(1);await expect.poll(()=>page.evaluate(()=>window.DrawSplatRecordingSupport.drafts.pending())).toBe(false);await page.reload();await expect(page.locator('#learnerFinishVoice')).toBeHidden();await expect(page.locator('#learnerVideoNote')).toContainText('Video note');expect((await saved(page)).panels[0].objects).toHaveLength(1)});
test('recovered video returns to its original page and keeps one undo step',async({page})=>{await record(page,'video');await page.locator('#videoNoteClose').click();await page.locator('#frameNavNext').click();await page.reload();await page.locator('#learnerVideoNote').click();await expect(page.locator('#videoNoteAdd')).toBeDisabled();await page.locator('#videoNoteReturnPage').click();await expect(page.locator('#videoNoteAdd')).toBeEnabled();await page.locator('#videoNoteAdd').click();let b=await saved(page);expect(b.active).toBe(0);expect(b.panels[0].objects).toHaveLength(1);expect(b.panels[1].objects).toHaveLength(0);await page.locator('#learnerUndo').click();expect((await saved(page)).panels[0].objects).toHaveLength(0)});
for(const kind of ['voice','video'])test(`${kind} discard stays discarded after a refresh`,async({page})=>{await record(page,kind);await page.locator(kind==='voice'?'#learnerDiscardAudio':'#videoNoteDiscard').click();await expect.poll(()=>page.evaluate(()=>window.DrawSplatRecordingSupport.drafts.pending())).toBe(false);await page.reload();await expect(page.locator('#learnerFinishVoice')).toBeHidden();await expect(page.locator('#learnerVideoNote')).toContainText('Video note');expect((await saved(page)).panels[0].objects).toHaveLength(0)});
test('teacher drafts do not appear in student view or a different board',async({page})=>{await record(page,'voice');await page.locator('#learnerAudioDialog .close').click();await record(page,'video');await page.locator('#videoNoteClose').click();await page.goto('/app/whiteboard.html?role=student&tools=select,audio,video');await expect(page.locator('#learnerFinishVoice')).toBeHidden();await expect(page.locator('#learnerVideoNote')).toContainText('Video note');await page.goto('/app/whiteboard.html?role=teacher');await expect(page.locator('#learnerFinishVoice')).toBeVisible();await expect(page.locator('#learnerVideoNote')).toContainText('Finish video');await page.locator('#jsonInput').setInputFiles({name:'other.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...fixture(),title:'Another board'}))});await expect(page.locator('#statusToast')).toContainText('Board loaded');await page.reload();await expect(page.locator('#learnerFinishVoice')).toBeHidden();await expect(page.locator('#learnerVideoNote')).toContainText('Video note')});
test('voice and video playback pause each other without losing position',async({page})=>{
const b=fixture();b.panels[0].objects=[{id:'a1',type:'audio',x:20,y:20,w:250,h:140,opacity:1,audioSrc:source,audioDuration:4},{id:'v1',type:'video',x:300,y:20,w:250,h:290,opacity:1,videoSrc:'data:video/mp4;base64,'+clip,videoName:'Demo'}];await page.locator('#jsonInput').setInputFiles({name:'media.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(b))});await expect(page.locator('#statusToast')).toContainText('Board loaded');const video=page.locator('.video-note-card video');await page.locator('.video-note-card').getByRole('button',{name:'Play',exact:true}).click();await expect.poll(()=>video.evaluate(v=>!v.paused)).toBe(true);await video.evaluate(v=>v.currentTime=.3);await page.locator('.audio-controls [data-audio-action=play]').click();await expect.poll(()=>video.evaluate(v=>v.paused)).toBe(true);expect(await video.evaluate(v=>v.currentTime)).toBeGreaterThanOrEqual(.3);await page.locator('.video-note-card').getByRole('button',{name:'Play',exact:true}).click();await expect(page.locator('.audio-playback-status')).toContainText('Paused')});
test('draft storage failure explains how to keep the answer',async({page})=>{await page.evaluate(()=>window.DrawSplatRecordingSupport.drafts.put=()=>Promise.reject(new Error('Storage full')));await page.locator('#learnerResponse').click();await page.locator('#learnerVoiceResponse').click();await page.locator('#learnerRecordAudio').click();await page.locator('#learnerRecordAudio').click();await expect(page.locator('#learnerAudioDraftStatus')).toContainText('Add it to your board before leaving');await page.locator('#learnerAddAudio').click();expect((await saved(page)).panels[0].objects).toHaveLength(1)});
test('expired voice drafts are not recovered',async({page})=>{await record(page,'voice');await page.evaluate(()=>new Promise((resolve,reject)=>{const request=indexedDB.open('drawsplat-recording-drafts',1);request.onsuccess=()=>{const db=request.result,tx=db.transaction('drafts','readwrite'),cursor=tx.objectStore('drafts').openCursor();cursor.onsuccess=()=>{const item=cursor.result;if(item){item.update({...item.value,expires:Date.now()-1000});item.continue()}};tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>reject(tx.error)}}));await page.reload();await expect(page.locator('#learnerFinishVoice')).toBeHidden()});
test('student recording permissions are rechecked before recovering drafts',async({page})=>{await page.goto('/app/whiteboard.html?role=student');await record(page,'voice');await page.locator('#learnerAudioDialog .close').click();await record(page,'video');await page.locator('#videoNoteClose').click();await page.evaluate(()=>{const b=JSON.parse(localStorage.getItem('drawsplat.autosave'));b.studentWorkspace.tools=['select'];localStorage.setItem('drawsplat.autosave',JSON.stringify(b))});await page.reload();await expect(page.locator('#learnerFinishVoice')).toBeHidden();await expect(page.locator('#learnerVideoNote')).toBeHidden();expect(await page.evaluate(()=>window.requests)).toHaveLength(0);await page.evaluate(()=>{const b=JSON.parse(localStorage.getItem('drawsplat.autosave'));b.studentWorkspace.tools=['select','audio','video'];localStorage.setItem('drawsplat.autosave',JSON.stringify(b))});await page.reload();await expect(page.locator('#learnerFinishVoice')).toBeVisible();await expect(page.locator('#learnerVideoNote')).toContainText('Finish video')});
test('switching between voice notes retains their paused positions',async({page})=>{const b=fixture();b.panels[0].objects=[{id:'a1',type:'audio',x:20,y:20,w:250,h:140,opacity:1,audioSrc:source,audioDuration:4},{id:'a2',type:'audio',x:300,y:20,w:250,h:140,opacity:1,audioSrc:source,audioDuration:4}];await page.locator('#jsonInput').setInputFiles({name:'voices.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(b))});await expect(page.locator('#statusToast')).toContainText('Board loaded');const first=page.locator('.audio-controls[data-audio-id=a1]'),second=page.locator('.audio-controls[data-audio-id=a2]');await first.locator('[data-audio-action=play]').click();await expect(first.locator('.audio-progress')).toBeEnabled();await expect.poll(async()=>+await first.locator('.audio-progress').inputValue()).toBeGreaterThan(0.2);await first.locator('.audio-progress').evaluate(el=>{el.value='1';el.dispatchEvent(new Event('input',{bubbles:true}))});await second.locator('[data-audio-action=play]').click();await expect(first.locator('.audio-playback-status')).toHaveText('Paused');expect(+await first.locator('.audio-progress').inputValue()).toBeGreaterThanOrEqual(1);await first.locator('[data-audio-action=play]').click();await expect(second.locator('.audio-playback-status')).toHaveText('Paused');expect(+await first.locator('.audio-progress').inputValue()).toBeGreaterThanOrEqual(1);await first.locator('[data-audio-action=stop]').click();await expect(first.locator('.audio-progress')).toHaveValue('0')});
test('active voice recording protects refresh until the draft is ready',async({page,browserName})=>{await page.locator('#learnerResponse').click();await page.locator('#learnerVoiceResponse').click();await page.locator('#learnerRecordAudio').click();await expect(page.locator('#learnerAudioStatus')).toContainText('Recording.');if(browserName==='firefox'){expect(await page.evaluate(()=>{const e=new Event('beforeunload',{cancelable:true});dispatchEvent(e);return e.defaultPrevented})).toBe(true)}else{const dialogType=new Promise(resolve=>page.once('dialog',async dialog=>{const type=dialog.type();await dialog.dismiss();resolve(type)}));const reloading=page.reload({timeout:3000}).catch(()=>{});expect(await dialogType).toBe('beforeunload');await reloading;}await expect(page.locator('#learnerAudioStatus')).toContainText('Recording.');await page.locator('#learnerRecordAudio').click();await expect(page.locator('#learnerAudioDraftStatus')).toContainText('kept on this device');await page.reload();await expect(page.locator('#learnerFinishVoice')).toBeVisible()});
test('voice recovery creates a new note if its original empty card was removed',async({page})=>{const b=fixture();b.panels[0].objects=[{id:'original',type:'audio',x:20,y:20,w:250,h:140,opacity:1,audioSrc:''}];await page.locator('#jsonInput').setInputFiles({name:'empty.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(b))});await expect(page.locator('#statusToast')).toContainText('Board loaded');await page.locator('.audio-controls').getByRole('button',{name:'Record my voice'}).click();await page.locator('#learnerRecordAudio').click();await page.locator('#learnerRecordAudio').click();await expect(page.locator('#learnerAudioDraftStatus')).toContainText('kept on this device');await page.locator('#learnerAudioDialog .close').click();await page.evaluate(()=>{const b=JSON.parse(localStorage.getItem('drawsplat.autosave'));b.panels[0].objects=[];localStorage.setItem('drawsplat.autosave',JSON.stringify(b))});await page.reload();await page.locator('#learnerFinishVoice').click();await page.locator('#learnerAddAudio').click();const objects=(await saved(page)).panels[0].objects;expect(objects).toHaveLength(1);expect(objects[0].id).not.toBe('original');expect(objects[0].audioSrc).toMatch(/^data:audio/)});
for(const kind of ['voice','video']){
  test(`${kind} Add waits for IndexedDB board storage before clearing recovery`,async({page})=>{
    await record(page,kind);
    await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='drawsplat.autosave')throw new DOMException('Full','QuotaExceededError');return original.call(this,key,value)}});
    await page.locator(kind==='voice'?'#learnerAddAudio':'#videoNoteAdd').click();
    await expect(page.locator(kind==='voice'?'#learnerAudioDialog':'#videoNoteDialog')).not.toBeVisible();
    await expect(page.locator('#saveStateChip')).toContainText('Saved');
    await expect.poll(()=>page.evaluate(()=>window.DrawSplatRecordingSupport.drafts.pending())).toBe(false);
    await page.reload();await expect(page.locator(kind==='voice'?'.audio-controls':'.video-note-card')).toHaveCount(1);
    if(kind==='voice')await expect(page.locator('#learnerFinishVoice')).toBeHidden();else await expect(page.locator('#learnerVideoNoteLabel')).toHaveText('Video note');
  });
  test(`${kind} failed Add retains recovery and a retry adds only one note`,async({page})=>{
    await record(page,kind);
    await page.evaluate(()=>{
      const original=Storage.prototype.setItem;window.restoreLocal=()=>Storage.prototype.setItem=original;
      Storage.prototype.setItem=function(key,value){if(key==='drawsplat.autosave')throw new DOMException('Full','QuotaExceededError');return original.call(this,key,value)};
      const put=IDBObjectStore.prototype.put;window.restoreBoardPut=()=>IDBObjectStore.prototype.put=put;
      IDBObjectStore.prototype.put=function(...args){if(this.name==='kv')throw new DOMException('Full','QuotaExceededError');return put.apply(this,args)};
    });
    await page.locator(kind==='voice'?'#learnerAddAudio':'#videoNoteAdd').click();
    await expect(page.locator(kind==='voice'?'#learnerAudioDraftStatus':'#videoNoteStatus')).toContainText('Save File');
    await expect(page.locator(kind==='voice'?'#learnerAudioDialog':'#videoNoteDialog')).toBeVisible();
    await page.evaluate(()=>{window.restoreLocal();window.restoreBoardPut()});
    await page.locator(kind==='voice'?'#learnerAddAudio':'#videoNoteAdd').click();
    await expect(page.locator(kind==='voice'?'#learnerAudioDialog':'#videoNoteDialog')).not.toBeVisible();
    await page.reload();await expect(page.locator(kind==='voice'?'.audio-controls':'.video-note-card')).toHaveCount(1);
  });
}
