const {test,expect}=require('@playwright/test');
test.use({storageState:{cookies:[],origins:[]}});
test.beforeEach(async({page})=>{await page.addInitScript(()=>{localStorage.setItem('drawsplat.welcomed','1');localStorage.setItem('drawsplat.consent.accepted','1');localStorage.setItem('drawsplat.startupTipDate',new Date().toISOString().slice(0,10))})});
const open=async page=>{await page.goto('/app/whiteboard.html');await expect(page.locator('#entryRoleDialog')).toBeVisible()};
test('first visitors choose student and the choice persists with fewer tools',async({page})=>{
 await open(page);await expect(page.locator('#entryRoleDialog .close')).toBeHidden();await page.keyboard.press('Escape');await expect(page.locator('#entryRoleDialog')).toBeVisible();await page.locator('#entryRoleStudent').click();await expect(page.locator('#entryRoleButton')).toHaveText('Student view');await expect(page.locator('#learnerStarters')).toBeHidden();await expect(page.locator('#learnerVideoNote')).toBeHidden();expect(await page.locator('#userMode').inputValue()).toBe('student');await page.reload();await expect(page.locator('#entryRoleDialog')).toBeHidden();await expect(page.locator('#entryRoleButton')).toHaveText('Student view');await expect(page.locator('#learnerStarters')).toBeHidden();
});
test('teacher choice exposes teaching and recording controls and can switch later',async({page})=>{
 await open(page);await page.locator('#entryRoleTeacher').click();await expect(page.locator('#learnerStarters')).toBeVisible();await expect(page.locator('#learnerVideoNote')).toBeVisible();await expect(page.locator('#entryRoleButton')).toHaveText('Teacher view');await page.locator('#entryRoleButton').click();await page.locator('#entryRoleStudent').click();await expect(page.locator('#learnerVideoNote')).toBeHidden();await page.locator('#entryRoleButton').click();await page.locator('#entryRoleTeacher').click();await expect(page.locator('#learnerStarters')).toBeVisible();await page.locator('#workspaceMode').evaluate(e=>{e.value='productivity';e.dispatchEvent(new Event('change',{bubbles:true}))});await page.reload();await expect(page.locator('#entryRoleDialog')).toBeHidden();await expect(page.locator('#entryRoleButton')).toHaveText('Teacher view');expect(await page.locator('#workspaceMode').inputValue()).toBe('productivity');
});
test('student links override a saved teacher choice and retain lesson permissions',async({page})=>{
 await open(page);await page.locator('#entryRoleTeacher').click();await page.goto('/app/whiteboard.html?role=student&tools=select,image,video&learner=beginner');await expect(page.locator('#entryRoleDialog')).toBeHidden();await expect(page.locator('#entryRoleButton')).toBeHidden();expect(await page.locator('#userMode').inputValue()).toBe('student');await expect(page.locator('#learnerVideoNote')).toBeVisible();await expect(page.locator('#learnerStarters')).toBeHidden();await page.locator('#entryRoleTeacher').evaluate(e=>e.click());expect(await page.locator('#userMode').inputValue()).toBe('student');expect(await page.evaluate(()=>localStorage.getItem('drawsplat.entryRole'))).toBe('teacher');
});
test('phone entry choices fit without horizontal scrolling',async({page})=>{
 await page.setViewportSize({width:390,height:844});await open(page);const r=await page.locator('#entryRoleDialog').boundingBox();expect(r.x).toBeGreaterThanOrEqual(0);expect(r.x+r.width).toBeLessThanOrEqual(390);await page.locator('#entryRoleStudent').click();await expect(page.locator('#entryRoleButton')).toBeVisible();
});
