const {chromium}=require('../../../node_modules/@playwright/test');const assert=require('node:assert/strict');const {execFileSync}=require('node:child_process');const {mkdtempSync}=require('node:fs');const {join}=require('node:path');
const origin=process.env.CLIPSPLAT_ORIGIN||'http://127.0.0.1:4186',dir=mkdtempSync('/tmp/clipsplat-video-frames-');
const fixture=(audio)=>{const path=join(dir,audio?'audio.mp4':'silent.mp4');const args=['-v','error','-f','lavfi','-i','color=blue:s=320x240:r=30:d=3'];if(audio)args.push('-f','lavfi','-i','sine=frequency=440:duration=3');args.push('-c:v','libx264');if(audio)args.push('-c:a','aac');args.push('-y',path);execFileSync('ffmpeg',args);return path;};const audio=fixture(true),silent=fixture(false);
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',args:['--no-sandbox','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});try{
const p=await browser.newPage({acceptDownloads:true,permissions:['camera','microphone']});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+'/solutions/clipsplat/');await p.waitForSelector('#settings',{state:'attached'});await p.locator('.workflow-step').evaluateAll(nodes=>nodes.forEach(node=>node.open=true));
assert.equal(await p.locator('#video-frame option').count(),5);assert.equal(await p.locator('#intro-frame option[value=confetti],#intro-frame option[value=stars],#intro-frame option[value=splat]').count(),0);
await p.locator('#intro-duration').fill('0');await p.locator('#outro-duration').fill('0');
for(const [index,style] of ['cinema','film-vintage','instant-classic','instant-scrapbook'].entries()){
const preset=index%2?'feed':'reel',fit=index<2?'contain':'crop';await p.locator('#preset').selectOption(preset);await p.locator('#fit').selectOption(fit);await p.locator('#file').setInputFiles(index%2?silent:audio);await p.waitForFunction(()=>!document.getElementById('export').disabled);await p.locator('#video-frame').selectOption(style);await p.waitForFunction(()=>!document.getElementById('export').disabled);await p.waitForTimeout(100);
const shot=await p.locator('#canvas').evaluate(c=>{const x=c.getContext('2d'),data=x.getImageData(0,0,c.width,c.height).data;for(let y=4;y<c.height*.22;y+=2)for(let xx=4;xx<c.width*.30;xx+=2){const i=(y*c.width+xx)*4;if(data[i]>180&&data[i+1]>120&&data[i+2]<100)return {x:xx,y,rgb:[...data.slice(i,i+3)],center:[...x.getImageData(c.width/2,c.height/2,1,1).data].slice(0,3)};}throw Error('No decorative gold pixel');});assert.ok(shot.center[2]>220&&shot.center[0]<30);await p.locator('#canvas').screenshot({path:join(dir,style+'.png')});
await p.locator('#export').click();await p.waitForFunction(()=>document.getElementById('download').style.display==='inline-block',null,{timeout:120000});const downloading=p.waitForEvent('download');await p.locator('#download').click();const output=join(dir,style+'.mp4');await(await downloading).saveAs(output);
const raw=execFileSync('ffmpeg',['-v','error','-ss','1','-i',output,'-vf',`crop=2:2:${shot.x}:${shot.y}`,'-frames:v','1','-pix_fmt','rgb24','-f','rawvideo','-']);assert.ok(shot.rgb.every((v,i)=>Math.abs(v-raw[i])<65),`${style} frame pixels ${shot.rgb} vs ${[...raw.slice(0,3)]}`);
const probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',output]));assert.ok(Math.abs(Number(probe.format.duration)-3)<.1);assert.equal(probe.streams.find(s=>s.codec_type==='video').codec_name,'h264');assert.equal(probe.streams.find(s=>s.codec_type==='audio').codec_name,'aac');assert.equal(probe.streams.find(s=>s.codec_type==='video').height,preset==='feed'?1350:1920);
const center=execFileSync('ffmpeg',['-v','error','-ss','1','-i',output,'-vf',`crop=2:2:540:${preset==='feed'?674:960}`,'-frames:v','1','-pix_fmt','rgb24','-f','rawvideo','-']);assert.ok(center[2]>220&&center[0]<30,'Export retains real video in the frame');
const pcm=execFileSync('ffmpeg',['-v','error','-ss','1','-i',output,'-t','0.3','-vn','-ac','1','-ar','48000','-f','s16le','-']);let energy=0;for(let i=0;i<pcm.length;i+=2)energy+=(pcm.readInt16LE(i)/32768)**2;const rms=Math.sqrt(energy/(pcm.length/2));assert.ok(index%2?rms<.001:rms>.02,'Preserve source audio or supply silence');
}
await p.locator('#camera').click();await p.waitForFunction(()=>!document.getElementById('record').disabled);await p.locator('#canvas').screenshot({path:join(dir,'camera-frame.png')});await p.locator('#close-camera').click();
await p.setViewportSize({width:390,height:844});await p.locator('#language').selectOption('ar');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('PASS: four video frames, imported/camera preview, actual MP4 border pixels, Reel/Feed, fit/crop, source/silent audio, removed basic styles, mobile/RTL',dir);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
