/* Three independent typing experiences; no network calls or student uploads. */
(() => {
'use strict';
const mode=document.body.dataset.page, $=id=>document.getElementById(id), t=(key)=>WidgetI18n.t(key), lang=()=>WidgetI18n.getLang();
const canvas=$('game'),ctx=canvas?.getContext('2d');
const carArt={};if(mode==='road')for(const key of ['player','rival','civilian']){const im=new Image();im.src='../typing-games/assets/'+key+'-car.png';carArt[key]=im}
let running=false,paused=false,ended=false,score=0,streak=0,shield=5,lines=0,best=0,elapsed=0,last=0,sound=true,audio=null;
const storageKey='drawsplat.typing.'+mode+'.best';
try{best=Number(localStorage.getItem(storageKey))||0}catch{}
const levels={beginner:{speed:65,spawn:3.5,fall:1.5},intermediate:{speed:90,spawn:2.6,fall:1},expert:{speed:115,spawn:2.1,fall:.7}};
const words={en:['sun map red cat dog road star book rain moon car leaf smile brave light'.split(' '),'mission signal engine coastal secret shadow compass rescue rocket explorer keyboard'.split(' '),'acceleration constellation determination headquarters imagination transformation'.split(' ')],es:['sol mapa rojo gato perro luna auto hoja risa luz'.split(' '),'misión señal motor costa secreto sombra rescate cohete teclado'.split(' '),'aceleración constelación imaginación transformación determinación'.split(' ')],vi:['mưa nắng mèo cây xe sao sách nhà lá vui'.split(' '),'bí mật,động cơ,ánh sáng,giải cứu,bàn phím,bờ biển'.split(','),'chòm sao,trí tưởng tượng,sự quyết tâm,sự biến đổi'.split(',')],ar:['شمس قمر قط كتاب سيارة نور طريق مطر'.split(' '),'إشارة محرك ساحل إنقاذ صاروخ لوحة ظل'.split(' '),'تسارع تصميم خيال كوكبة استكشاف'.split(' ')],zh:[['太阳','小猫','汽车','月亮','雨水','星星'],['信号','发动机','秘密','救援','键盘','海岸'],['加速度','星座','想象力','决心','探索']],uh:['धूप चाँद बिल्ली किताब गाड़ी घर पेड़'.split(' '),'संकेत इंजन बचाव रॉकेट रहस्य समुद्र'.split(' '),'कल्पना दृढ़ता परिवर्तन नक्षत्र त्वरण'.split(' ')]};
const vocabulary=()=>mode==='road'&&$('subject').value!=='general'?(window.CipherVocabulary||[]).filter(v=>v.band===$('vocabBand').value&&($('subject').value==='all'||v.subject===$('subject').value)):[];
const usedWords=()=>{if(vocabulary().length)return vocabulary().map(v=>v.word);const i=['beginner','intermediate','expert'].indexOf($('difficulty')?.value||'beginner');return(words[lang()]||words.en)[i]};
function pickWord(){const list=usedWords();const occupied=mode==='road'?road.traffic.map(v=>v.word):mode==='blocks'?[block?.word,...grid.flat().filter(Boolean).map(v=>v.word)]:[];const pool=list.filter(w=>!occupied.includes(w));return(pool.length?pool:list)[Math.floor(Math.random()*(pool.length||list.length))]}
const cfg=()=>levels[$('difficulty')?.value||'beginner'];
const norm=s=>s.normalize('NFC').trim().toLocaleLowerCase();
async function beep(freq=650,report=false){
 if(!sound)return false;
 try{
  const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error('unavailable');
  audio??=new Audio();await audio.resume();if(!sound)return false;if(audio.state!=='running')throw Error('suspended');
  const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type='triangle';o.frequency.setValueAtTime(freq,audio.currentTime);
  g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.18,audio.currentTime+.015);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.25);
  o.onended=()=>{o.disconnect();g.disconnect()};o.start();o.stop(audio.currentTime+.27);
  if(report&&$('audioStatus'))$('audioStatus').textContent=t('audioReady');return true;
 }catch{if($('audioStatus'))$('audioStatus').textContent=t('audioUnavailable');else feedback('audioUnavailable');return false}
}
let definitionTimer;
function showDefinition(word){
 const entry=vocabulary().find(v=>norm(v.word)===word);if(!entry)return;
 const card=$('definitionCard');clearTimeout(definitionTimer);card.hidden=false;card.classList.remove('definition-flash');void card.offsetWidth;card.classList.add('definition-flash');
 $('definitionWord').textContent=entry.word;$('definitionText').textContent=entry.definition;
 $('definitionSource').href=entry.source;$('definitionSource').textContent=t(entry.subject)+' · '+entry.standard+' · TEKS';
 definitionTimer=setTimeout(()=>card.classList.remove('definition-flash'),4500);
}
function resetVocabulary(){clearTimeout(definitionTimer);$('definitionCard').hidden=true;$('vocabBand').disabled=$('subject').value==='general';$('vocabNote').hidden=$('subject').value==='general';if(running||ended)start();else initRoad();roadTargets()}

function feedback(key){$('feedback').textContent=t(key)}
function hud(){if(mode==='coach')return;for(const [id,v] of Object.entries({score:Math.floor(score),best,streak,lives:shield,lines}))if($(id))$(id).textContent=v;if(Math.floor(score)>best){best=Math.floor(score);$('best').textContent=best;try{localStorage.setItem(storageKey,String(best))}catch{}}}
function overlay(title,text,button='start'){if(!canvas)return;$('overlay').hidden=false;$('overlayTitle').textContent=t(title);$('overlayText').textContent=text;$('overlayStart').textContent=t(button)}
function sessionButtons(){if($('start'))$('start').textContent=t(running?'restart':'start');$('pause').textContent=t(paused?'resume':'pause');$('pause').disabled=(!running&&mode!=='coach')||ended;$('sound').textContent=t(sound?'soundOn':'soundOff');$('sound').setAttribute('aria-pressed',String(sound))}
function finish(){running=false;ended=true;beep(160);sessionButtons();overlay('over',t('score')+': '+Math.floor(score),'restart')}
function start(){beep(520);if($('definitionCard'))$('definitionCard').hidden=true;score=0;streak=0;shield=5;lines=0;elapsed=0;ended=false;paused=false;running=true;$('word').value='';$('feedback').textContent='';mode==='road'?initRoad():initBlocks();$('overlay').hidden=true;hud();sessionButtons();$('word').focus({preventScroll:true})}
function pause(){if(mode==='coach'){if(ended)return;paused=!paused;$('practice').disabled=paused;sessionButtons();return}if(!running)return;paused=!paused;if(paused)overlay('paused',t(mode+'.keys'),'resume');else{$('overlay').hidden=true;$('word').focus({preventScroll:true})}sessionButtons()}
function submit(){if(!running||paused||ended)return;const value=norm($('word').value);if(!value)return;const hit=mode==='road'?zapRoad(value):zapBlock(value);if(hit){streak++;score+=100+value.length*10+streak*5;feedback('hit');beep();$('word').value='';}else{streak=0;feedback('nomatch');beep(180)}hud();$('word').focus({preventScroll:true})}
// Cipher Chase: a continuous overhead road, steering and typed attacks.
let road={traffic:[],lane:1,x:450,scroll:0,timer:1,invulnerable:0,smoke:0,smokeCooldown:0,shots:[],distance:0};
const laneX=n=>340+n*110;
function initRoad(){road={traffic:[],lane:1,x:450,scroll:0,timer:.4,invulnerable:2,smoke:0,smokeCooldown:0,shots:[],distance:0}}
function steer(dir){road.lane=Math.max(0,Math.min(2,road.lane+dir))}
function smoke(){if(road.smokeCooldown>0)return;road.smoke=2.2;road.invulnerable=2.2;road.smokeCooldown=12;road.traffic=road.traffic.filter(v=>{if(v.enemy&&v.y>260){score+=40;return false}return true});beep(320);hud()}
function spawnTraffic(){const enemy=elapsed<1||Math.random()>.28;let lane=Math.floor(Math.random()*3);road.traffic.push({lane,x:laneX(lane),y:elapsed<1?100:-70,enemy,word:enemy?pickWord():'',hit:false});roadTargets();}
function zapRoad(value){const v=road.traffic.filter(v=>v.enemy&&!v.hit&&norm(v.word)===value).sort((a,b)=>b.y-a.y)[0];if(!v)return false;v.hit=true;showDefinition(value);roadTargets();road.shots.push({x:road.x,y:550,tx:v.x,ty:v.y,life:.24});return true}
function roadTargets(){if(!$('targets'))return;const value=road.traffic.filter(v=>v.enemy&&!v.hit&&v.y>=70).map(v=>v.word).join(' · ');if($('targets').textContent!==value)$('targets').textContent=value}
function updateRoad(dt){const speed=cfg().speed+Math.min(35,elapsed*.15);road.scroll=(road.scroll+speed*dt)%100;road.distance+=speed*dt*.03;road.x+=(laneX(road.lane)-road.x)*Math.min(1,dt*10);road.invulnerable=Math.max(0,road.invulnerable-dt);road.smoke=Math.max(0,road.smoke-dt);road.smokeCooldown=Math.max(0,road.smokeCooldown-dt);road.timer-=dt;if(road.timer<=0){spawnTraffic();road.timer=cfg().spawn}for(const v of road.traffic){v.y+=speed*dt;if(!v.hit&&Math.abs(v.x-road.x)<52&&Math.abs(v.y-560)<70){v.hit=true;if(!road.invulnerable){shield--;streak=0;road.invulnerable=1.8;feedback('damage');beep(170);if(shield<=0){finish();return}}}}road.traffic=road.traffic.filter(v=>v.y<740&&(!v.hit||road.shots.some(s=>s.tx===v.x&&Math.abs(s.ty-v.y)<45)));roadTargets();road.shots.forEach(s=>s.life-=dt);road.shots=road.shots.filter(s=>s.life>0);const smokeButton=document.querySelector('[data-action=smoke]');if(smokeButton){smokeButton.disabled=road.smokeCooldown>0;smokeButton.textContent=road.smokeCooldown>0?t('smoke.wait')+' '+Math.ceil(road.smokeCooldown)+'s':t('smoke')}score+=dt*2;hud()}
function car(x,y,color,player=false){const im=carArt[player?'player':color==='#ef786d'?'rival':'civilian'];if(im?.complete&&im.naturalWidth){ctx.drawImage(im,x-31,y-53,62,106);return}ctx.save();ctx.translate(x,y);ctx.fillStyle='#10243c66';ctx.fillRect(-28,-40,64,100);ctx.fillStyle='#152635';for(const dx of [-30,23]){ctx.fillRect(dx,-28,8,23);ctx.fillRect(dx,20,8,23)}ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(-24,-48,48,96,9);ctx.fill();ctx.fillStyle='#a6d9e5';ctx.beginPath();ctx.roundRect(-18,-18,36,25,5);ctx.fill();ctx.fillStyle='#183446';ctx.fillRect(-18,16,36,16);ctx.fillStyle='#ffea99';ctx.fillRect(-21,-43,10,5);ctx.fillRect(11,-43,10,5);ctx.fillStyle='#f46c64';ctx.fillRect(-20,39,9,5);ctx.fillRect(11,39,9,5);if(player){ctx.fillStyle='#087e8b';ctx.fillRect(-3,-42,6,29)}ctx.restore()}
function label(text,x,y,color='#fff',size=24){ctx.save();ctx.font=`bold ${size}px 'Trebuchet MS',Arial`;ctx.textAlign='center';ctx.textBaseline='middle';const w=Math.max(70,ctx.measureText(text).width+26);ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x-w/2,y-20,w,40,7);ctx.fill();ctx.fillStyle='#153b59';ctx.fillText(text,x,y);ctx.restore()}
function drawRoad(){ctx.fillStyle='#217981';ctx.fillRect(0,0,900,640);ctx.fillStyle='#58b5c3';for(let i=0;i<8;i++){ctx.fillRect(25,((i*95+road.scroll*1.2)%740)-80,150,3)}ctx.fillStyle='#d0bf87';ctx.fillRect(180,0,78,640);ctx.fillStyle='#3c745e';ctx.fillRect(632,0,268,640);ctx.fillStyle='#344d5d';ctx.fillRect(270,0,360,640);ctx.fillStyle='#dce5e5';ctx.fillRect(275,0,5,640);ctx.fillRect(620,0,5,640);ctx.strokeStyle='#c4d9df';ctx.lineWidth=3;ctx.setLineDash([35,65]);ctx.lineDashOffset=-road.scroll;for(const x of [395,505]){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,640);ctx.stroke()}ctx.setLineDash([]);for(let i=0;i<9;i++){const y=(i*95+road.scroll)%750-55;for(const x of [235,685,820]){ctx.fillStyle='#194e43';ctx.beginPath();ctx.moveTo(x,y-22);ctx.lineTo(x-20,y+25);ctx.lineTo(x+20,y+25);ctx.fill();ctx.fillStyle='#317965';ctx.beginPath();ctx.moveTo(x-4,y-20);ctx.lineTo(x-17,y+18);ctx.lineTo(x+5,y+18);ctx.fill()}}for(const v of road.traffic){if(v.hit)continue;car(v.x,v.y,v.enemy?'#ef786d':'#7dc9ed');if(v.enemy)label(v.word,v.x,v.y-76,norm($('word').value)&&norm(v.word).startsWith(norm($('word').value))?'#ffdf87':'#fff',22);else{ctx.fillStyle='#fff';ctx.font='14px Arial';ctx.textAlign='center';ctx.fillText(t('civilian'),v.x,v.y-60);ctx.textAlign='start'}}if(road.smoke>0){ctx.fillStyle='#dce7ebb8';for(let i=0;i<8;i++){ctx.beginPath();ctx.arc(road.x+Math.sin(i)*45,590+i*15,28+i*3,0,Math.PI*2);ctx.fill()}}ctx.save();ctx.globalAlpha=road.invulnerable&&Math.floor(elapsed*8)%2!==0?.55:1;car(road.x,560,'#faf6e7',true);ctx.restore();for(const s of road.shots){ctx.strokeStyle='#ffdc6e';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.tx,s.ty);ctx.stroke();ctx.fillStyle='#ffd56a';ctx.beginPath();ctx.arc(s.tx,s.ty,24,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#133644e8';ctx.fillRect(12,12,210,65);ctx.fillStyle='#fff';ctx.font='bold 19px Arial';ctx.fillText(Math.floor(road.distance)+' km',26,38);ctx.font='15px Arial';ctx.fillText(t(road.smokeCooldown>0?'smoke.wait':'smoke.ready')+(road.smokeCooldown>0?' '+Math.ceil(road.smokeCooldown)+'s':''),26,63)}
// Wordfall Reactor: full pieces, seven-piece bag, wall kicks, hold and ghost.
const shapes=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[0,1,1],[1,1,0]],[[1,1,0],[0,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]]];
const colors=['#54d3eb','#f7cf63','#b997ef','#77d3a4','#f9848e','#7eb4f3','#ffb575'];
let grid=[],block=null,held=null,queue=[],bag=[],canHold=true,fall=0,pieceID=0,particles=[];
function definition(){if(!bag.length){bag=[0,1,2,3,4,5,6];for(let i=6;i>0;i--){const j=Math.floor(Math.random()*(i+1));[bag[i],bag[j]]=[bag[j],bag[i]]}}const type=bag.pop();return{type,shape:shapes[type].map(r=>r.slice()),color:colors[type],word:pickWord()}}
function initBlocks(){grid=Array.from({length:20},()=>Array(10).fill(null));block=null;held=null;bag=[];queue=[];fall=0;pieceID=0;particles=[];for(let i=0;i<3;i++)queue.push(definition());spawn()}
function spawn(def){const d=def||queue.shift();if(!def)queue.push(definition());block={...d,shape:d.shape.map(r=>r.slice()),x:Math.floor((10-d.shape[0].length)/2),y:0,id:++pieceID};canHold=true;fall=0;if(collides(block)){finish()}updateTargets()}
function cells(p,fn){p.shape.forEach((r,dy)=>r.forEach((v,dx)=>{if(v)fn(p.x+dx,p.y+dy)}))}
function collides(p,dx=0,dy=0,shape=p.shape){let result=false;shape.forEach((r,y)=>r.forEach((v,x)=>{if(!v)return;const xx=p.x+x+dx,yy=p.y+y+dy;if(xx<0||xx>=10||yy>=20||(yy>=0&&grid[yy][xx]))result=true}));return result}
function move(dx,dy){if(!block||collides(block,dx,dy))return false;block.x+=dx;block.y+=dy;return true}
function rotate(){const s=block.shape[0].map((_,i)=>block.shape.map(r=>r[i]).reverse());for(const k of [0,-1,1,-2,2])if(!collides(block,k,0,s)){block.shape=s;block.x+=k;break}}
function drop(){while(move(0,1))score+=2;lock()}
function hold(){if(!canHold)return;const d={type:block.type,color:block.color,word:block.word,shape:shapes[block.type].map(r=>r.slice())};if(held){const old=held;held=d;spawn(old)}else{held=d;spawn()}canHold=false}
function clearRows(){let n=0;grid=grid.filter(r=>{if(r.every(Boolean)){n++;return false}return true});while(grid.length<20)grid.unshift(Array(10).fill(null));if(n){lines+=n;score+=[0,100,300,500,800][n]||n*250;beep(950)}}
function lock(){cells(block,(x,y)=>{if(y>=0)grid[y][x]={id:block.id,word:block.word,color:block.color}});clearRows();spawn();hud()}
function zapBlock(value){let found=false;const ids=new Set();if(norm(block.word)===value){found=true;cells(block,(x,y)=>particles.push({x:24+x*34,y:54+y*34,life:.5,color:block.color}));block=null}for(const c of grid.flat())if(c&&norm(c.word)===value)ids.add(c.id);if(ids.size){found=true;grid.forEach((r,y)=>r.forEach((c,x)=>{if(c&&ids.has(c.id)){particles.push({x:24+x*34,y:54+y*34,life:.5,color:c.color});grid[y][x]=null}}))}if(!found)return false;if(!block)spawn();clearRows();updateTargets();return true}
function updateTargets(){if(!$('targets'))return;$('targets').replaceChildren();const list=[...new Set(grid.flat().filter(Boolean).map(v=>v.word))];for(const word of list){const span=document.createElement('span');span.textContent=word;$('targets').append(span)}}
function mini(p,x,y){if(!p)return;p.shape.forEach((r,yy)=>r.forEach((v,xx)=>{if(v)tile(x+xx*21,y+yy*21,20,p.color)}))}
function tile(x,y,size,color,ghost=false){ctx.fillStyle=ghost?'#ffffff0d':color;ctx.strokeStyle=ghost?'#ffe193':'#ffffff55';ctx.lineWidth=ghost?2:1;ctx.beginPath();ctx.roundRect(x+2,y+2,size-4,size-4,4);ctx.fill();ctx.stroke();if(!ghost){ctx.fillStyle='#ffffff55';ctx.fillRect(x+5,y+5,size-10,3)}}
function drawBlocks(){ctx.fillStyle='#182943';ctx.fillRect(0,0,600,760);ctx.fillStyle='#0d1d33';ctx.fillRect(20,50,348,688);for(let y=0;y<20;y++)for(let x=0;x<10;x++){ctx.strokeStyle='#c6d8ff16';ctx.strokeRect(24+x*34,54+y*34,34,34);if(grid[y][x])tile(24+x*34,54+y*34,34,grid[y][x].color)}if(block){let gy=block.y;while(!collides({...block,y:gy},0,1))gy++;cells({...block,y:gy},(x,y)=>tile(24+x*34,54+y*34,34,block.color,true));cells(block,(x,y)=>tile(24+x*34,54+y*34,34,block.color));label(block.word,194,27,norm($('word').value)&&norm(block.word).startsWith(norm($('word').value))?'#ffdf87':'#fff',23)}ctx.fillStyle='#d5e2f4';ctx.font='bold 22px Arial';ctx.fillText(t('held'),394,70);mini(held,400,95);if(held){ctx.font='17px Arial';ctx.fillText(held.word,394,175)}ctx.font='bold 22px Arial';ctx.fillText(t('nextpiece'),394,245);queue.forEach((p,i)=>{mini(p,400,275+i*140);ctx.fillStyle='#d5e2f4';ctx.font='17px Arial';ctx.fillText(p.word,394,352+i*140)});for(const p of particles){ctx.globalAlpha=p.life*2;tile(p.x,p.y,34,p.color);ctx.globalAlpha=1}}
function updateBlocks(dt){fall+=dt;const delay=Math.max(.25,cfg().fall-lines*.025);if(fall>=delay){fall=0;if(!move(0,1))lock()}particles.forEach(p=>{p.life-=dt;p.y-=dt*70});particles=particles.filter(p=>p.life>0)}
// Story Sprint: active-time clock, exact character feedback, deliberate next step.
let passages=[],passageIndex=0,target='',typedTime=0,started=false,completed=false,customSet=false;
function builtin(){const set=TypingPassageTranslations[lang()]||TypingPassages;passages=(set[$('grade').value]||set.k2).map(p=>({...p}));customSet=false;fillSelect();setPassage(0)}
function fillSelect(){$('passageSelect').replaceChildren();passages.forEach((p,i)=>{const o=document.createElement('option');o.value=i;o.textContent=p.title;$('passageSelect').append(o)})}
function setPassage(i){passageIndex=i;target=passages[i].text.normalize('NFC').replace(/\s+/g,' ').trim();$('passageTitle').textContent=passages[i].title;$('passageSelect').value=String(i);$('practice').value='';$('practice').disabled=false;$('practice').readOnly=false;typedTime=0;started=false;completed=false;ended=false;paused=false;running=true;feedback('ready');renderPassage();coachStats();sessionButtons()}
function renderPassage(){const text=$('practice').value.normalize('NFC');$('passage').replaceChildren();for(let i=0;i<target.length;i++){const span=document.createElement('span');span.textContent=target[i];span.className=i<text.length?(target[i]===text[i]?'correct':'wrong'):i===text.length?'current':'';$('passage').append(span)}}
function coachStats(){const text=$('practice').value.normalize('NFC');let wrong=0;for(let i=0;i<text.length;i++)if(text[i]!==target[i])wrong++;const correct=text.length-wrong;$('wpm').textContent=typedTime>=1?Math.round(correct/5/(typedTime/60)):0;$('accuracy').textContent=(text.length?Math.round(correct/text.length*100):100)+'%';$('errors').textContent=wrong;$('progress').textContent=Math.min(100,Math.floor(correct/Math.max(1,target.length)*100))+'%';if(!completed&&text===target&&target.length){completed=true;ended=true;$('practice').readOnly=true;feedback('complete');beep(900);sessionButtons()}}
function accentKeys(){$('accentKeys').replaceChildren();if(lang()==='es')for(const c of ['á','é','í','ó','ú','ü','ñ','¿','¡']){const b=document.createElement('button');b.textContent=c;b.type='button';b.addEventListener('click',()=>{if(paused||ended)return;const input=$('practice');input.setRangeText(c,input.selectionStart,input.selectionEnd,'end');input.dispatchEvent(new Event('input',{bubbles:true}));input.focus({preventScroll:true})});$('accentKeys').append(b)}}
function parseCSV(text){let rows=[],r=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){r.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;r.push(cell);if(r.some(x=>x.trim()))rows.push(r);r=[];cell=''}else cell+=c}r.push(cell);if(r.some(x=>x.trim()))rows.push(r);return rows}
function rowsToPassages(rows){if(rows[0]&&/^(title|name)$/i.test(rows[0][0].trim())&&/^(text|passage|words)$/i.test((rows[0][1]||'').trim()))rows=rows.slice(1);return rows.map((r,i)=>({title:r.length>1?r[0]:t('passage')+' '+(i+1),text:r.length>1?r.slice(1).join(' '):r[0]})).filter(p=>p.text.trim())}
function parseJSON(text){const data=JSON.parse(text),arr=Array.isArray(data)?data:data.passages;if(!Array.isArray(arr))throw Error();return arr.map((p,i)=>typeof p==='string'?{title:t('passage')+' '+(i+1),text:p}:{title:String(p.title||p.name||t('passage')),text:Array.isArray(p.words)?p.words.join(' '):String(p.text||p.passage||p.words||'')}).filter(p=>p.text.trim())}
async function parseXLSX(file){const zip=await JSZip.loadAsync(await file.arrayBuffer());const parser=new DOMParser(),strings=[];const shared=zip.file('xl/sharedStrings.xml');if(shared)parser.parseFromString(await shared.async('text'),'application/xml').querySelectorAll('si').forEach(si=>strings.push([...si.querySelectorAll('t')].map(n=>n.textContent).join('')));const sheet=zip.file('xl/worksheets/sheet1.xml');if(!sheet)throw Error();const xml=parser.parseFromString(await sheet.async('text'),'application/xml');return rowsToPassages([...xml.querySelectorAll('row')].map(row=>{const cells=[];row.querySelectorAll('c').forEach(c=>{const ref=c.getAttribute('r')||'A1';let n=0;for(const ch of ref.replace(/\d/g,''))n=n*26+ch.charCodeAt(0)-64;let value=c.querySelector('v')?.textContent||'';if(c.getAttribute('t')==='s')value=strings[Number(value)]||'';if(c.getAttribute('t')==='inlineStr')value=[...c.querySelectorAll('t')].map(n=>n.textContent).join('');cells[n-1]=value});return Array.from({length:cells.length},(_,i)=>cells[i]||'')}))}
function load(items){if(!items.length||items.length>200||items.some(p=>typeof p.text!=='string'||p.text.length>10000))throw Error();passages=items;customSet=true;fillSelect();setPassage(0);feedback('loaded')}
function loadText(text,kind='txt'){if(kind==='json'||/^[\[{]/.test(text.trim()))load(parseJSON(text));else if(kind==='csv')load(rowsToPassages(parseCSV(text)));else load([{title:t('passage'),text}])}
function action(name){if(!running||paused||ended)return;if(mode==='road'){if(name==='left')steer(-1);if(name==='right')steer(1);if(name==='smoke')smoke()}else if(mode==='blocks'){if(name==='left')move(-1,0);if(name==='right')move(1,0);if(name==='rotate')rotate();if(name==='hold')hold();if(name==='drop')drop();if(name==='down')move(0,1);hud()}}
function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(running&&!paused&&!ended){if(mode==='coach'){if(started&&!completed){typedTime+=dt;coachStats()}}else{elapsed+=dt;mode==='road'?updateRoad(dt):updateBlocks(dt)}}if(canvas){if(mode==='road')drawRoad();else if(grid.length)drawBlocks()}requestAnimationFrame(loop)}
$('pause').addEventListener('click',pause);$('reset').addEventListener('click',()=>mode==='coach'?setPassage(passageIndex):start());$('sound').addEventListener('click',()=>{sound=!sound;beep(650,true);sessionButtons()});
if($('testSound'))$('testSound').addEventListener('click',()=>{sound=true;sessionButtons();beep(880,true)});
if(mode==='road')for(const id of ['subject','vocabBand'])$(id).addEventListener('change',resetVocabulary);
if(mode==='coach'){
 // Restrict bulk insertion only in scored practice; classroom imports remain available.
 const blockPaste=e=>{e.preventDefault();feedback('typeOnly')};
 for(const event of ['paste','drop'])$('practice').addEventListener(event,blockPaste);
 $('practice').addEventListener('beforeinput',e=>{if(['insertFromPaste','insertFromPasteAsQuotation','insertFromDrop','insertReplacementText'].includes(e.inputType))blockPaste(e)});
 $('practice').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='v'||e.shiftKey&&e.key==='Insert')blockPaste(e)});
 $('practice').addEventListener('pointerdown',()=>{if(sound&&!audio)beep(400)});
 $('grade').addEventListener('change',builtin);$('passageSelect').addEventListener('change',()=>setPassage(Number($('passageSelect').value)));$('next').addEventListener('click',()=>setPassage((passageIndex+1)%passages.length));$('practice').addEventListener('input',()=>{if(paused||ended)return;started=$('practice').value.length>0||started;renderPassage();coachStats()});$('load').addEventListener('click',()=>{try{const text=$('custom').value.trim();if(!text)throw Error();loadText(text,text.includes(',')&&text.includes('\n')?'csv':'txt')}catch{feedback('invalid')}});$('file').addEventListener('change',async()=>{const file=$('file').files[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error();const kind=file.name.split('.').pop().toLowerCase();if(kind==='xlsx')load(await parseXLSX(file));else loadText(await file.text(),kind)}catch{feedback('invalid')}finally{$('file').value=''}});builtin();accentKeys();
}else{
 $('start').addEventListener('click',start);$('overlayStart').addEventListener('click',()=>paused?pause():start());$('fire').addEventListener('click',submit);$('difficulty').addEventListener('change',()=>{if(running||ended)start();else{mode==='road'?initRoad():initBlocks()}});$('word').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();submit()}});document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{action(b.dataset.action);$('word').focus({preventScroll:true})}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();pause();return}if(e.target.tagName==='SELECT'||e.target.tagName==='BUTTON')return;if(e.key===' '&&e.target===$('word')&&$('word').value.length)return;const key={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'rotate',ArrowDown:'down',' ':mode==='road'?'smoke':'drop',Shift:'hold'}[e.key];if(key){e.preventDefault();action(key)}});mode==='road'?initRoad():initBlocks();overlay('ready',t(mode+'.how'));sessionButtons();hud();
}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused&&!ended)pause()});
window.addEventListener('widget-i18n:changed',()=>{if(mode==='coach'){accentKeys();if(!customSet)builtin();else{renderPassage();coachStats()}}else{running=false;paused=false;ended=false;mode==='road'?initRoad():initBlocks();if($('definitionCard'))$('definitionCard').hidden=true;overlay('ready',t(mode+'.how'))}sessionButtons();feedback('ready')});
requestAnimationFrame(loop);
})();
