/* Quiz & Flashcard Studio — locale dictionary. */
(function(){
const en={
'doc.title':'Quiz & Flashcard Studio | DrawSplat Tools','header.eyebrow':'DrawSplat<sup class="tm">TM</sup> Tools','header.h1':'Quiz & Flashcard Studio','header.tagline':'Create a quiz, import a question bank, run a self-paced classroom round, export the content, then transfer the same questions into study flashcards.','header.home':'Home',
'nav.build':'Build','nav.play':'Play Quiz','nav.flashcards':'Flashcards','nav.reports':'Reports','stat.questions':'Questions','stat.points':'Points','stat.cards':'Cards','stat.pointsShort':'pts',
'common.yes':'Yes','common.no':'No','common.clear':'Clear','common.previous':'Previous','common.next':'Next','common.edit':'Edit','common.delete':'Delete',
'build.setup':'Quiz Setup','build.title':'Title','build.seconds':'Seconds per question','build.mode':'Play mode','build.selfPaced':'Self-paced','build.teacherLed':'Teacher-led','build.shuffleQuestions':'Shuffle questions','build.shuffleAnswers':'Shuffle answers','build.question':'Question','build.questionPh':'What is retrieval practice?','build.correct':'Correct answer','build.correctPh':'Pulling information from memory','build.distractors':'Distractors or alternate answers','build.distractorsPh':'Re-reading notes\nHighlighting text\nCopying definitions','build.type':'Type','build.add':'Add Question','build.update':'Update','build.import':'Import Questions','build.importHint':"CSV/TSV columns: question, answer, wrong1, wrong2, wrong3, type, points, notes. XLSX/ODS use the first sheet. JSON accepts this app's export.",'build.sampleCsv':'Sample CSV','build.sampleJson':'Sample JSON','build.sampleSet':'Sample Data Set','build.paste':'Paste Import','build.pastePh':'Question,Answer,Wrong 1,Wrong 2\n2 + 2?,4,3,5','build.importPaste':'Import Pasted Text','build.loadSample':'Load Sample','build.saveDraft':'Save Draft','build.loadDraft':'Load Draft',
'type.multiple':'Multiple choice','type.trueFalse':'True / False','type.short':'Short answer','type.multiplechoice':'Multiple choice','type.truefalse':'True / False','type.shortanswer':'Short answer',
'bank.title':'Question Bank','bank.search':'Search questions','bank.start':'Start Quiz','bank.transfer':'Transfer to Flashcards','bank.exportJson':'Export JSON','bank.exportCsv':'Export CSV','bank.exportXlsx':'Export XLSX','bank.clearAll':'Clear All','bank.empty':'No questions yet. Add one, paste CSV text, or import a file.',
'play.controls':'Play Controls','play.addPlayer':'Add Player','play.addTeam':'Add Team','play.restart':'Restart','play.teamName':'Team name','play.playerName':'Player / team name','play.shareLink':'Standalone quiz link','play.copyLink':'Copy Link','play.shareHint':'The link embeds the quiz in the URL hash for a self-paced online run. It does not create a live server room or collect remote responses.','play.submit':'Submit','play.leaderboard':'Leaderboard','play.startEmpty':'Start a quiz from the Build tab.','play.shortPh':'Type an answer','play.correctAnswer':'Correct answer','play.noPlayers':'No players yet.','play.sharedQuiz':'Shared Quiz',
'flash.title':'Flashcard Maker','flash.hint':'Cards are generated from quiz questions. The front is the question and the back is the correct answer plus optional context.','flash.printScope':'Print','flash.printAll':'Entire deck','flash.printCurrent':'Current card only','flash.shuffle':'Shuffle','flash.exportCsv':'Export Cards CSV','flash.printCards':'Print Cards','flash.flip':'Flip','flash.count':'{i} / {n} cards','flash.zero':'0 cards','flash.front':'Front','flash.back':'Back','flash.none':'No cards yet','flash.printEmpty':'Transfer quiz questions to flashcards before printing.',
'reports.export':'Export Report CSV','reports.clear':'Clear Reports','reports.empty':'No responses yet. Run a quiz to collect local report rows.','reports.time':'Time','reports.player':'Player','reports.answer':'Answer','reports.result':'Result','reports.correct':'Correct','reports.incorrect':'Incorrect',
'footer.html':'DrawSplat<sup>TM</sup> Quiz & Flashcard Studio. Browser-only imports, exports, quiz runs, and flashcards. <a href="../../pages/features.html">Explore more</a>.',
'status.needQuestion':'Add both a question and a correct answer.','status.added':'Question added.','status.updated':'Question updated.','status.pasted':'pasted text','status.importFailed':'Import failed: {err}','status.noUsable':'No usable questions found in {name}.','status.imported':'Imported {n} question(s) from {name}.','status.draftSaved':'Draft saved in this browser.','status.noDraft':'No saved draft found.','status.draftLoaded':'Draft loaded.','status.addBeforeStart':'Add questions before starting.','status.sharedFailed':'Shared quiz link could not be loaded.','status.cleared':'Question bank cleared.','status.noSample':'No sample data set is available.','status.sampleLoaded':'Loaded {title}.','confirm.clearAll':'Clear all questions?'
};
const es={...en,
'doc.title':'Estudio de cuestionarios y tarjetas | Herramientas DrawSplat','header.eyebrow':'Herramientas DrawSplat<sup class="tm">TM</sup>','header.h1':'Estudio de cuestionarios y tarjetas','header.tagline':'Crea un cuestionario, importa un banco de preguntas, realiza una ronda en clase, exporta el contenido y convierte las mismas preguntas en tarjetas de estudio.','header.home':'Inicio',
'nav.build':'Crear','nav.play':'Jugar','nav.flashcards':'Tarjetas','nav.reports':'Informes','stat.questions':'Preguntas','stat.points':'Puntos','stat.cards':'Tarjetas','stat.pointsShort':'pts',
'common.yes':'Sí','common.no':'No','common.clear':'Limpiar','common.previous':'Anterior','common.next':'Siguiente','common.edit':'Editar','common.delete':'Eliminar',
'build.setup':'Configuración','build.title':'Título','build.seconds':'Segundos por pregunta','build.mode':'Modo de juego','build.selfPaced':'A ritmo propio','build.teacherLed':'Dirigido por docente','build.shuffleQuestions':'Mezclar preguntas','build.shuffleAnswers':'Mezclar respuestas','build.question':'Pregunta','build.questionPh':'¿Qué es la práctica de recuperación?','build.correct':'Respuesta correcta','build.correctPh':'Recordar información de memoria','build.distractors':'Distractores o respuestas alternativas','build.distractorsPh':'Releer apuntes\nSubrayar texto\nCopiar definiciones','build.type':'Tipo','build.add':'Agregar pregunta','build.update':'Actualizar','build.import':'Importar preguntas','build.importHint':'Columnas CSV/TSV: question, answer, wrong1, wrong2, wrong3, type, points, notes. XLSX/ODS usa la primera hoja. JSON acepta la exportación de esta app.','build.sampleCsv':'CSV de muestra','build.sampleJson':'JSON de muestra','build.sampleSet':'Conjunto de muestra','build.paste':'Pegar importación','build.pastePh':'Question,Answer,Wrong 1,Wrong 2\n2 + 2?,4,3,5','build.importPaste':'Importar texto pegado','build.loadSample':'Cargar muestra','build.saveDraft':'Guardar borrador','build.loadDraft':'Cargar borrador',
'type.multiple':'Opción múltiple','type.trueFalse':'Verdadero / Falso','type.short':'Respuesta corta','type.multiplechoice':'Opción múltiple','type.truefalse':'Verdadero / Falso','type.shortanswer':'Respuesta corta',
'bank.title':'Banco de preguntas','bank.search':'Buscar preguntas','bank.start':'Iniciar cuestionario','bank.transfer':'Transferir a tarjetas','bank.exportJson':'Exportar JSON','bank.exportCsv':'Exportar CSV','bank.exportXlsx':'Exportar XLSX','bank.clearAll':'Limpiar todo','bank.empty':'Aún no hay preguntas. Agrega una, pega texto CSV o importa un archivo.',
'play.controls':'Controles','play.addPlayer':'Agregar jugador','play.addTeam':'Agregar equipo','play.restart':'Reiniciar','play.teamName':'Nombre del equipo','play.playerName':'Jugador / equipo','play.shareLink':'Enlace independiente del cuestionario','play.copyLink':'Copiar enlace','play.shareHint':'El enlace incrusta el cuestionario en la URL para una sesión en línea a ritmo propio. No crea una sala en vivo ni recopila respuestas remotas.','play.submit':'Enviar','play.leaderboard':'Tabla de posiciones','play.startEmpty':'Inicia un cuestionario desde la pestaña Crear.','play.shortPh':'Escribe una respuesta','play.correctAnswer':'Respuesta correcta','play.noPlayers':'Aún no hay jugadores.','play.sharedQuiz':'Cuestionario compartido',
'flash.title':'Creador de tarjetas','flash.hint':'Las tarjetas se generan desde las preguntas del cuestionario. El frente es la pregunta y el reverso es la respuesta correcta con contexto opcional.','flash.printScope':'Imprimir','flash.printAll':'Todo el mazo','flash.printCurrent':'Solo la tarjeta actual','flash.shuffle':'Mezclar','flash.exportCsv':'Exportar tarjetas CSV','flash.printCards':'Imprimir tarjetas','flash.flip':'Voltear','flash.count':'{i} / {n} tarjetas','flash.zero':'0 tarjetas','flash.front':'Frente','flash.back':'Reverso','flash.none':'Aún no hay tarjetas','flash.printEmpty':'Transfiere preguntas a tarjetas antes de imprimir.',
'reports.export':'Exportar informe CSV','reports.clear':'Limpiar informes','reports.empty':'Aún no hay respuestas. Ejecuta un cuestionario para recopilar filas de informe local.','reports.time':'Hora','reports.player':'Jugador','reports.answer':'Respuesta','reports.result':'Resultado','reports.correct':'Correcto','reports.incorrect':'Incorrecto',
'footer.html':'Estudio de cuestionarios y tarjetas DrawSplat<sup>TM</sup>. Importaciones, exportaciones, cuestionarios y tarjetas solo en el navegador. <a href="../../pages/features.html">Explorar más</a>.',
'status.needQuestion':'Agrega una pregunta y una respuesta correcta.','status.added':'Pregunta agregada.','status.updated':'Pregunta actualizada.','status.pasted':'texto pegado','status.importFailed':'Error al importar: {err}','status.noUsable':'No se encontraron preguntas utilizables en {name}.','status.imported':'Se importaron {n} pregunta(s) desde {name}.','status.draftSaved':'Borrador guardado en este navegador.','status.noDraft':'No se encontró un borrador guardado.','status.draftLoaded':'Borrador cargado.','status.addBeforeStart':'Agrega preguntas antes de iniciar.','status.sharedFailed':'No se pudo cargar el enlace del cuestionario compartido.','status.cleared':'Banco de preguntas limpiado.','confirm.clearAll':'¿Limpiar todas las preguntas?'
};
const vi={...en,'header.eyebrow':'Công cụ DrawSplat<sup class="tm">TM</sup>','header.h1':'Câu hỏi & thẻ học','header.home':'Trang chủ','nav.build':'Tạo','nav.play':'Làm quiz','nav.flashcards':'Thẻ học','nav.reports':'Báo cáo','stat.questions':'Câu hỏi','stat.points':'Điểm','stat.cards':'Thẻ','common.yes':'Có','common.no':'Không','common.clear':'Xóa','common.previous':'Trước','common.next':'Tiếp','build.setup':'Thiết lập quiz','build.title':'Tiêu đề','build.question':'Câu hỏi','build.correct':'Đáp án đúng','bank.title':'Ngân hàng câu hỏi','bank.search':'Tìm câu hỏi','bank.start':'Bắt đầu quiz','bank.transfer':'Chuyển sang thẻ học','play.leaderboard':'Bảng điểm','flash.title':'Tạo thẻ học','flash.printAll':'Cả bộ thẻ','flash.printCurrent':'Chỉ thẻ hiện tại','reports.answer':'Đáp án','reports.correct':'Đúng','reports.incorrect':'Sai'};
const ar={...en,'header.eyebrow':'أدوات DrawSplat<sup class="tm">TM</sup>','header.h1':'استوديو الاختبارات والبطاقات','header.home':'الرئيسية','nav.build':'إنشاء','nav.play':'تشغيل الاختبار','nav.flashcards':'بطاقات','nav.reports':'تقارير','stat.questions':'أسئلة','stat.points':'نقاط','stat.cards':'بطاقات','common.yes':'نعم','common.no':'لا','common.clear':'مسح','common.previous':'السابق','common.next':'التالي','build.setup':'إعداد الاختبار','build.title':'العنوان','build.question':'السؤال','build.correct':'الإجابة الصحيحة','bank.title':'بنك الأسئلة','bank.search':'بحث في الأسئلة','bank.start':'بدء الاختبار','bank.transfer':'تحويل إلى بطاقات','play.leaderboard':'لوحة الصدارة','flash.title':'صانع البطاقات','flash.printAll':'كل البطاقات','flash.printCurrent':'البطاقة الحالية فقط','reports.answer':'الإجابة','reports.correct':'صحيح','reports.incorrect':'غير صحيح'};
const zh={...en,'header.eyebrow':'DrawSplat<sup class="tm">TM</sup> 工具','header.h1':'测验与抽认卡工作室','header.home':'首页','nav.build':'创建','nav.play':'开始测验','nav.flashcards':'抽认卡','nav.reports':'报告','stat.questions':'问题','stat.points':'分数','stat.cards':'卡片','common.yes':'是','common.no':'否','common.clear':'清除','common.previous':'上一题','common.next':'下一题','build.setup':'测验设置','build.title':'标题','build.question':'问题','build.correct':'正确答案','bank.title':'题库','bank.search':'搜索问题','bank.start':'开始测验','bank.transfer':'转为抽认卡','play.leaderboard':'排行榜','flash.title':'抽认卡制作器','flash.printAll':'整套卡片','flash.printCurrent':'仅当前卡片','reports.answer':'答案','reports.correct':'正确','reports.incorrect':'错误'};
const uh={...en,'header.h1':'क्विज़ और फ्लैशकार्ड स्टूडियो','header.home':'होम','nav.build':'बनाएं','nav.play':'क्विज़ खेलें','nav.flashcards':'फ्लैशकार्ड','nav.reports':'रिपोर्ट','stat.questions':'प्रश्न','stat.points':'अंक','stat.cards':'कार्ड','common.yes':'हाँ','common.no':'नहीं','common.clear':'साफ करें','common.previous':'पिछला','common.next':'अगला','build.setup':'क्विज़ सेटअप','build.title':'शीर्षक','build.question':'प्रश्न','build.correct':'सही उत्तर','bank.title':'प्रश्न बैंक','bank.search':'प्रश्न खोजें','bank.start':'क्विज़ शुरू करें','bank.transfer':'फ्लैशकार्ड में भेजें','play.leaderboard':'लीडरबोर्ड','flash.title':'फ्लैशकार्ड मेकर','flash.printAll':'पूरा डेक','flash.printCurrent':'केवल वर्तमान कार्ड','reports.answer':'उत्तर','reports.correct':'सही','reports.incorrect':'गलत'};
WidgetI18n.register('quiz-flashcard-studio',{en,es,vi,ar,zh,uh});
})();
