(() => {
'use strict';
const $=id=>document.getElementById(id),t=k=>WidgetI18n.t(k),storage='drawsplat.paws.progress.v1';
const lessons=[['f','j'],['d','k'],['s','l'],['a',';'],['f','j','d','k','s','l','a',';'],['g','h'],['r','u','e','i'],['t','y','w','o','q','p'],['c','v','b','n','m','x','z'],['cat','dog','pet','paw'],['sun','run','fun','hop','nap'],['kitten','puppy','happy','little','friend']];
let progress={little:{},growing:{},big:{}},index=0,targets=[],step=0,char=0,mistakes=0,paused=false,complete=false,sound=false,audio=null;
try{const saved=JSON.parse(localStorage.getItem(storage));for(const age of Object.keys(progress))if(saved&&typeof saved[age]==='object'&&saved[age])for(const [k,v] of Object.entries(saved[age]))if(Number(k)>=0&&Number(k)<12&&v>=1&&v<=3)progress[age][k]=v}catch{}
const age=()=>$('age').value;
const unlocked=i=>i===0||!!progress[age()][i-1];
const title=i=>t('trail')+' '+(i+1)+' · '+t('trail'+(Math.floor(i/3)+1));
function save(){try{localStorage.setItem(storage,JSON.stringify(progress))}catch{}}
function stars(v){return '★'.repeat(v)+'☆'.repeat(3-v)}
function maps(){const select=$('trailSelect');select.replaceChildren();$('trailMap').replaceChildren();for(let i=0;i<lessons.length;i++){const option=document.createElement('option');option.value=i;option.textContent=title(i)+(unlocked(i)?'':' 🔒');option.disabled=!unlocked(i);select.append(option);const b=document.createElement('button');b.textContent=title(i);b.disabled=!unlocked(i);b.className=i===index?'current-trail':'';b.setAttribute('aria-label',title(i)+' '+(unlocked(i)?stars(progress[age()][i]||0):t('locked')));const small=document.createElement('small');small.textContent=unlocked(i)?stars(progress[age()][i]||0):'🔒 '+t('locked');b.append(small);b.addEventListener('click',()=>start(i));$('trailMap').append(b)}select.value=index;$('starCount').textContent='★ '+Object.values(progress[age()]).reduce((a,b)=>a+b,0)}
function keyboard(){const container=$('keyboard');container.replaceChildren();for(const row of ['qwertyuiop','asdfghjkl;','zxcvbnm']){const div=document.createElement('div');div.className='key-row';for(const c of row){const b=document.createElement('button');b.type='button';b.textContent=c.toUpperCase();b.dataset.key=c;b.setAttribute('aria-label',t('letter')+' '+c.toUpperCase());b.addEventListener('click',()=>press(c));div.append(b)}container.append(div)}}
const fingers={li:'fgrtvcb',lm:'edc',lr:'wsx',lp:'qaz',ri:'jhuynm',rm:'ik',rr:'ol',rp:'p;'};
function finger(key){if(key==='c')return'lm';if(key==='v'||key==='b')return'li';for(const [name,chars] of Object.entries(fingers))if(chars.includes(key))return name;return'li'}
function currentKey(){return targets[step]?.[char]||''}
function practiceKeys(){const div=$('practiceKeys');div.replaceChildren();if(age()!=='little'||index>=5)return;for(const key of lessons[index]){const b=document.createElement('button');b.type='button';b.textContent=key.toUpperCase();b.dataset.key=key;b.addEventListener('click',()=>press(key));div.append(b)}}
function prompt(){if(complete){$('keyPrompt').textContent='★';return}const text=targets[step]||'';$('keyPrompt').replaceChildren();for(let i=0;i<text.length;i++){const span=document.createElement('span');span.textContent=text[i].toUpperCase();span.className=i<char?'done':i===char?'now':'';$('keyPrompt').append(span)}const key=currentKey();$('fingerHint').textContent=t('finger')+': '+t(finger(key));for(const b of document.querySelectorAll('#keyboard button, #practiceKeys button')){b.classList.toggle('glow',b.dataset.key===key);b.disabled=paused||complete;b.setAttribute('aria-current',b.dataset.key===key?'true':'false')}$('trailProgress').max=targets.length;$('trailProgress').value=step;$('trailLabel').textContent=title(index)+' · '+step+'/'+targets.length;$('petRunner').style.left=(4+(step/targets.length)*72)+'%'}
function speak(){if(!('speechSynthesis' in window)||complete||paused)return;const key=currentKey();if(!key)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(key===';'?'semicolon':key);u.lang='en-US';u.rate=.7;speechSynthesis.speak(u)}
function beep(){if(!sound)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=600;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.start();o.stop(audio.currentTime+.13)}catch{}}
function start(i){if(!unlocked(i))return;index=i;document.querySelector('.pet-landscape').src='../typing-games/assets/world-'+(Math.floor(i/3)+1)+'.webp';targets=[];const count={little:8,growing:12,big:16}[age()],pool=lessons[i];for(let n=0;n<count;n++)targets.push(pool[n%pool.length]);step=0;char=0;mistakes=0;complete=false;paused=false;$('pawsPause').disabled=false;$('celebration').hidden=true;document.body.classList.remove('paws-paused');$('pawsPause').textContent=t('pause');$('pawsFeedback').textContent=t('ready');maps();practiceKeys();prompt();document.querySelector('.paws-stage').focus({preventScroll:true});if(sound)speak()}
function win(){complete=true;const correct=targets.reduce((n,w)=>n+w.length,0),accuracy=correct/(correct+mistakes),earned=accuracy>=.95?3:accuracy>=.8?2:1;progress[age()][index]=Math.max(progress[age()][index]||0,earned);save();maps();$('trailProgress').value=targets.length;$('trailLabel').textContent=title(index)+' · '+targets.length+'/'+targets.length;$('keyPrompt').textContent='★';$('petRunner').style.left='76%';$('earnedStars').textContent=stars(earned);$('celebration').hidden=false;$('nextTrail').disabled=index===lessons.length-1;$('pawsFeedback').textContent=t('traildone');for(const b of document.querySelectorAll('#keyboard button, #practiceKeys button'))b.disabled=true;$('fingerHint').textContent='';$('pawsPause').disabled=true}
function press(key){if(paused||complete)return;if(key.toLowerCase()!==currentKey()){mistakes++;$('pawsFeedback').textContent=t('trykey');return}char++;beep();$('pawsFeedback').textContent=t('keepgoing');const runner=$('petRunner');runner.classList.remove('hop');void runner.offsetWidth;runner.classList.add('hop');if(char>=targets[step].length){step++;char=0;if(step>=targets.length){win();return}}prompt();if(sound&&age()==='little')speak()}
$('pet').addEventListener('change',()=>{$('petRunner').src='../typing-games/assets/'+$('pet').value+'.png';$('petRunner').alt=t($('pet').value);document.querySelector('.paws-stage').focus({preventScroll:true})});$('age').addEventListener('change',()=>start(0));$('trailSelect').addEventListener('change',()=>{start(Number($('trailSelect').value));$('pawsPause').disabled=false});$('nextTrail').addEventListener('click',()=>{if(index<11){start(index+1);$('pawsPause').disabled=false}});$('retry').addEventListener('click',()=>{start(index);$('pawsPause').disabled=false});$('pawsReset').addEventListener('click',()=>{start(index);$('pawsPause').disabled=false});$('pawsPause').addEventListener('click',()=>{if(complete)return;paused=!paused;document.body.classList.toggle('paws-paused',paused);$('pawsPause').textContent=t(paused?'resume':'pause');$('pawsFeedback').textContent=t(paused?'paused':'ready');prompt()});$('pawsSound').addEventListener('click',()=>{sound=!sound;$('pawsSound').setAttribute('aria-pressed',String(sound));$('pawsSound').textContent=t(sound?'soundOn':'soundOff');if(sound)speak()});$('listen').addEventListener('click',speak);
document.addEventListener('keydown',e=>{if(['SELECT','INPUT','TEXTAREA'].includes(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey||e.repeat)return;if(/^[a-z;]$/i.test(e.key)){e.preventDefault();press(e.key)}});
window.addEventListener('widget-i18n:changed',()=>{maps();keyboard();practiceKeys();prompt();$('petRunner').alt=t($('pet').value);$('pawsSound').textContent=t(sound?'soundOn':'soundOff');$('pawsPause').textContent=t(paused?'resume':'pause');$('pawsFeedback').textContent=t(complete?'traildone':paused?'paused':'ready')});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&!paused&&!complete){paused=true;$('pawsPause').textContent=t('resume');document.body.classList.add('paws-paused');prompt()}});
keyboard();start(0);$('petRunner').alt=t('kitten');
})();
