const crypto = require('node:crypto');
const {jsonValue}=require('./json-value');
const {passwordRecord}=require('./password');
const {safeString,normalizeEmail,isValidEmail,createRateLimiter}=require('./security');
const hash=value=>crypto.createHash('sha256').update(String(value)).digest();
function attachClassroomRoutes(app,pool,{basePath,auth,checkBoardSafety,pepper}) {
 const base=basePath+'/classrooms';
 const route=fn=>(req,res,next)=>Promise.resolve(fn(req,res)).catch(next);
 const signed=auth.requireRoles(['teacher','student','district_admin','campus_admin']);
 const teacher=auth.requireRoles(['teacher','district_admin','campus_admin']);
 const student=auth.requireRoles(['student']);
 const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
 async function owned(id,user){const [rows]=await pool.execute('SELECT * FROM classrooms WHERE id=? AND teacher_user_id=?',[id,user]);if(!rows[0])fail(404,'Classroom not found.');return rows[0];}
 async function member(id,user){const [rows]=await pool.execute('SELECT c.* FROM classrooms c LEFT JOIN classroom_members m ON m.classroom_id=c.id AND m.user_id=? WHERE c.id=? AND (c.teacher_user_id=? OR m.user_id=?)',[user,id,user,user]);if(!rows[0])fail(404,'Classroom not found.');return rows[0];}
 async function invitation(id,code){if(!/^\d+$/.test(String(id))||!/^([a-f0-9]{48})$/.test(String(code)))fail(400,'Invalid class invitation.');const [rows]=await pool.execute('SELECT id FROM classrooms WHERE id=? AND invite_hash=?',[id,hash(code)]);if(!rows.length)fail(404,'Class invitation not found.');return rows[0].id;}
 async function boardJson(board){if(!board||!Array.isArray(board.panels)||!board.panels.length)fail(400,'A whiteboard with at least one page is required.');const json=JSON.stringify(board);if(Buffer.byteLength(json)>Number(process.env.MAX_BOARD_JSON_BYTES||20*1024*1024))fail(413,'Board is too large.');const [rows]=await pool.query("SELECT config_json FROM compliance_config WHERE config_key='main'");if(!checkBoardSafety(board,jsonValue(rows[0]?.config_json)||{}).ok)fail(422,'School content rules blocked this board.');return json;}
 app.post(base+'/enroll',createRateLimiter({scope:'class-enroll',max:20}),route(async(req,res)=>{
  if(process.env.ROSTER_ONLY==='true')fail(403,'Student accounts are provisioned by your district administrator.');
  const {classroomId,code,password,displayName}=req.body;const email=normalizeEmail(req.body.email);
  const id=await invitation(classroomId,code);
  if(!isValidEmail(email)||String(password||'').length<12||String(password).length>200)fail(400,'Use a valid email and a password of 12–200 characters.');
  const {salt,hash:pw}=passwordRecord(password,pepper);const conn=await pool.getConnection();
  try{await conn.beginTransaction();const [created]=await conn.execute("INSERT INTO users (email,display_name,student_name,role,provider,password_hash,password_salt) VALUES (?,?,?,'student','email',?,?)",[email,safeString(displayName,190),safeString(displayName,190),pw,salt]);await conn.execute('INSERT INTO classroom_members (classroom_id,user_id) VALUES (?,?)',[id,created.insertId]);await conn.commit();res.json({ok:true});}
  catch(error){await conn.rollback();if(error.code==='ER_DUP_ENTRY')fail(409,'Account already exists. Sign in, then join with the invitation.');throw error;}finally{conn.release();}
 }));
 app.post(base+'/join',student,route(async(req,res)=>{if(process.env.ROSTER_ONLY==='true')fail(403,'Class membership is managed by your district administrator.');const id=await invitation(req.body.classroomId,req.body.code);await pool.execute('INSERT IGNORE INTO classroom_members (classroom_id,user_id) VALUES (?,?)',[id,req.dsUser.id]);res.json({ok:true});}));
 app.get(base,signed,route(async(req,res)=>{const [classes]=await pool.execute('SELECT DISTINCT c.id,c.title,c.teacher_user_id AS teacherUserId FROM classrooms c LEFT JOIN classroom_members m ON m.classroom_id=c.id WHERE c.teacher_user_id=? OR m.user_id=? ORDER BY c.id DESC',[req.dsUser.id,req.dsUser.id]);res.json({ok:true,classes});}));
 app.post(base,teacher,route(async(req,res)=>{const title=safeString(req.body.title,200);if(!title)fail(400,'Enter a class name.');const code=crypto.randomBytes(24).toString('hex');const [out]=await pool.execute('INSERT INTO classrooms (teacher_user_id,title,invite_hash) VALUES (?,?,?)',[req.dsUser.id,title,hash(code)]);res.json({ok:true,classroomId:out.insertId,code});}));
 app.post(base+'/:id/invitation',teacher,route(async(req,res)=>{await owned(req.params.id,req.dsUser.id);const code=crypto.randomBytes(24).toString('hex');await pool.execute('UPDATE classrooms SET invite_hash=? WHERE id=?',[hash(code),req.params.id]);res.json({ok:true,classroomId:Number(req.params.id),code});}));
 app.get(base+'/:id/members',teacher,route(async(req,res)=>{await owned(req.params.id,req.dsUser.id);const [members]=await pool.execute('SELECT u.id,u.display_name AS displayName,u.email FROM classroom_members m JOIN users u ON u.id=m.user_id WHERE m.classroom_id=? AND u.deleted_at IS NULL',[req.params.id]);res.json({ok:true,members});}));
 app.delete(base+'/:id/members/:user',teacher,route(async(req,res)=>{await owned(req.params.id,req.dsUser.id);await pool.execute('DELETE FROM classroom_members WHERE classroom_id=? AND user_id=?',[req.params.id,req.params.user]);res.json({ok:true});}));
 app.get(base+'/:id/assignments',signed,route(async(req,res)=>{await member(req.params.id,req.dsUser.id);const [assignments]=await pool.execute('SELECT id,title,created_at AS createdAt FROM classroom_assignments WHERE classroom_id=? ORDER BY id DESC',[req.params.id]);res.json({ok:true,assignments});}));
 app.post(base+'/:id/assignments',teacher,route(async(req,res)=>{await owned(req.params.id,req.dsUser.id);const json=await boardJson(req.body.board);const title=safeString(req.body.title||req.body.board.title,200)||'Untitled assignment';const [out]=await pool.execute('INSERT INTO classroom_assignments (classroom_id,title,board_json) VALUES (?,?,?)',[req.params.id,title,json]);res.json({ok:true,assignmentId:out.insertId});}));
 app.get(base+'/:id/assignments/:assignment',signed,route(async(req,res)=>{await member(req.params.id,req.dsUser.id);const [rows]=await pool.execute('SELECT id,title,board_json AS board FROM classroom_assignments WHERE classroom_id=? AND id=?',[req.params.id,req.params.assignment]);if(!rows[0])fail(404,'Assignment not found.');res.json({ok:true,...rows[0],board:jsonValue(rows[0].board)});}));
 app.put(base+'/:id/assignments/:assignment/submission',student,route(async(req,res)=>{
  await member(req.params.id,req.dsUser.id);const [assignment]=await pool.execute('SELECT id FROM classroom_assignments WHERE classroom_id=? AND id=?',[req.params.id,req.params.assignment]);if(!assignment.length)fail(404,'Assignment not found.');
  const {board,revision}=req.body;if(!Number.isSafeInteger(revision)||revision<0)fail(400,'Submission revision is required.');const json=await boardJson(board);
  if(revision===0){try{await pool.execute('INSERT INTO classroom_submissions (assignment_id,student_user_id,board_json) VALUES (?,?,?)',[req.params.assignment,req.dsUser.id,json]);}catch(error){if(error.code==='ER_DUP_ENTRY')fail(409,'Submission changed. Reload your class before resubmitting.');throw error;}}
  else{const [result]=await pool.execute('UPDATE classroom_submissions SET board_json=?,revision=revision+1,submitted_at=CURRENT_TIMESTAMP WHERE assignment_id=? AND student_user_id=? AND revision=?',[json,req.params.assignment,req.dsUser.id,revision]);if(!result.affectedRows)fail(409,'Submission changed. Reload your class before resubmitting.');}
  res.json({ok:true,revision:revision+1});
 }));
 app.get(base+'/:id/submissions',signed,route(async(req,res)=>{const cls=await member(req.params.id,req.dsUser.id);const isOwner=String(cls.teacher_user_id)===String(req.dsUser.id);const [submissions]=await pool.execute('SELECT s.assignment_id AS assignmentId,s.student_user_id AS studentUserId,u.display_name AS displayName,a.title,s.revision,s.feedback,s.submitted_at AS submittedAt FROM classroom_submissions s JOIN classroom_assignments a ON a.id=s.assignment_id JOIN users u ON u.id=s.student_user_id WHERE a.classroom_id=?'+(isOwner?'':' AND s.student_user_id=?')+' ORDER BY s.submitted_at DESC',isOwner?[req.params.id]:[req.params.id,req.dsUser.id]);res.json({ok:true,submissions});}));
 app.get(base+'/:id/submissions/:assignment/:user',signed,route(async(req,res)=>{const cls=await member(req.params.id,req.dsUser.id);if(String(cls.teacher_user_id)!==String(req.dsUser.id)&&String(req.params.user)!==String(req.dsUser.id))fail(404,'Submission not found.');const [rows]=await pool.execute('SELECT s.board_json AS board,s.feedback,s.revision FROM classroom_submissions s JOIN classroom_assignments a ON a.id=s.assignment_id WHERE a.classroom_id=? AND s.assignment_id=? AND s.student_user_id=?',[req.params.id,req.params.assignment,req.params.user]);if(!rows[0])fail(404,'Submission not found.');res.json({ok:true,...rows[0],board:jsonValue(rows[0].board)});}));
 app.put(base+'/:id/submissions/:assignment/:user/feedback',teacher,route(async(req,res)=>{await owned(req.params.id,req.dsUser.id);const [result]=await pool.execute('UPDATE classroom_submissions s JOIN classroom_assignments a ON a.id=s.assignment_id SET s.feedback=? WHERE a.classroom_id=? AND s.assignment_id=? AND s.student_user_id=?',[safeString(req.body.feedback,2000),req.params.id,req.params.assignment,req.params.user]);res.json({ok:true});}));
}
module.exports={attachClassroomRoutes};
