const $=s=>document.querySelector(s),enc=new TextEncoder(),dec=new TextDecoder(),MAGIC=enc.encode('NIVORA1!'),ITERATIONS=600000;
let mode='file',operation='encrypt',selectedEntries=[],resultBlob=null,resultName='',resultText='',resultFiles=[];
const els={fileInput:$('#fileInput'),folderInput:$('#folderInput'),drop:$('#dropZone'),fileCard:$('#fileCard'),text:$('#textInput'),password:$('#password'),run:$('#runButton'),error:$('#errorMessage'),result:$('#resultPanel')};
document.querySelectorAll('.mode-tab').forEach(btn=>{btn.addEventListener('click',()=>selectMode(btn));btn.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const tabs=[...document.querySelectorAll('.mode-tab')],index=e.key==='Home'?0:e.key==='End'?tabs.length-1:(tabs.indexOf(btn)+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[index].focus();selectMode(tabs[index])})});
function selectMode(btn){mode=btn.dataset.mode;document.querySelectorAll('.mode-tab').forEach(b=>{const active=b===btn;b.classList.toggle('active',active);b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1});$('#fileInputArea').classList.toggle('hidden',mode!=='file');$('#textInputArea').classList.toggle('hidden',mode!=='text');resetResult();sync()}
document.querySelectorAll('.op').forEach(btn=>btn.addEventListener('click',()=>{operation=btn.dataset.op;document.querySelectorAll('.op').forEach(b=>{const active=b===btn;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)});$('#dropTitle').textContent=operation==='encrypt'?'Drop files or a folder into the vault':'Drop one .ciphersplat package to unlock';$('#dropSub').textContent=operation==='encrypt'?'recursive paths are detected automatically':'folder structure will be restored after authentication';$('#chooseFolder').classList.toggle('hidden',operation==='decrypt');els.fileInput.multiple=operation==='encrypt';els.text.placeholder=operation==='encrypt'?'Paste a private note, recovery code, or message…':'Paste a CipherSplat encrypted text package…';clearSelection();resetResult();sync()}));
els.fileInput.addEventListener('change',()=>setEntries([...els.fileInput.files].map(file=>({file,path:file.name}))));
els.folderInput.addEventListener('change',()=>setEntries([...els.folderInput.files].map(file=>({file,path:file.webkitRelativePath||file.name}))));
$('#chooseFiles').addEventListener('click',e=>{e.stopPropagation();els.fileInput.click()});
$('#chooseFolder').addEventListener('click',e=>{e.stopPropagation();els.folderInput.click()});
['dragenter','dragover'].forEach(type=>els.drop.addEventListener(type,e=>{e.preventDefault();els.drop.classList.add('drag')}));
['dragleave','drop'].forEach(type=>els.drop.addEventListener(type,e=>{e.preventDefault();els.drop.classList.remove('drag')}));
els.drop.addEventListener('drop',async e=>{const found=[];for(const item of e.dataTransfer.items){const entry=item.webkitGetAsEntry?.();if(entry)await walkEntry(entry,'',found)}setEntries(found.length?found:[...e.dataTransfer.files].map(file=>({file,path:file.name})))});
$('#removeFile').addEventListener('click',()=>{clearSelection();resetStatus();sync()});
els.text.addEventListener('input',()=>{$('#charCount').textContent=els.text.value.length;sync()});
els.password.addEventListener('input',()=>{updateStrength();sync()});
$('#showPassword').addEventListener('click',e=>{const showing=els.password.type==='password';els.password.type=showing?'text':'password';e.currentTarget.setAttribute('aria-label',showing?'Hide password':'Show password');e.currentTarget.setAttribute('aria-pressed',showing)});
$('#generatePassword').addEventListener('click',()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%&*+-=?',limit=256-256%chars.length;let password='';while(password.length<24){const bytes=crypto.getRandomValues(new Uint8Array(32));for(const byte of bytes){if(byte<limit)password+=chars[byte%chars.length];if(password.length===24)break}}els.password.value=password;els.password.type='text';updateStrength();sync()});
els.run.addEventListener('click',runLarge);
$('#downloadResult').addEventListener('click',downloadResult);
$('#copyResult').addEventListener('click',async()=>{await navigator.clipboard.writeText(resultText);$('#copyResult').textContent='Copied ✓';setTimeout(()=>$('#copyResult').textContent=resultFiles.length?'Copy result':'Copy encrypted text',1600)});
function clearSelection(){selectedEntries=[];els.fileInput.value='';els.folderInput.value='';els.fileCard.classList.add('hidden');els.drop.classList.remove('hidden')}
function setEntries(entries){if(!entries.length)return;if(operation==='decrypt'&&entries.length>1){els.error.textContent='Choose one encrypted .prism package to decrypt.';return}selectedEntries=entries;const folder=entries.length>1||entries[0].path.includes('/'),total=entries.reduce((n,e)=>n+e.file.size,0);$('#fileName').textContent=folder?`${entries[0].path.split('/')[0]} · ${entries.length} files`:entries[0].file.name;$('#fileSize').textContent=`${formatBytes(total)}${folder?' · recursive package':''}`;els.drop.classList.add('hidden');els.fileCard.classList.remove('hidden');resetResult();sync()}
async function walkEntry(entry,prefix,out){if(entry.isFile){const file=await new Promise((resolve,reject)=>entry.file(resolve,reject));out.push({file,path:prefix+file.name});return}if(entry.isDirectory){const reader=entry.createReader();let batch;do{batch=await new Promise((resolve,reject)=>reader.readEntries(resolve,reject));for(const child of batch)await walkEntry(child,prefix+entry.name+'/',out)}while(batch.length)}}
function sync(){els.run.disabled=!(mode==='file'?selectedEntries.length:els.text.value.trim())||!els.password.value;$('#runLabel').textContent=`${operation==='encrypt'?'Encrypt':'Decrypt'} ${mode==='file'&&selectedEntries.length>1?'folder':mode}`}
function updateStrength(){const p=els.password.value;let score=0;if(p.length>=12)score++;if(p.length>=18)score++;if(/[A-Z]/.test(p)&&/[a-z]/.test(p))score++;if(/\d/.test(p)&&/[^\w]/.test(p))score++;const labels=['ENTER A PASSWORD','WEAK','FAIR','STRONG','EXCELLENT'],colors=['#ddd','#ef5479','#f0aa3c','#32c99a','#18bfc9'];$('#strengthBar').style.width=score*25+'%';$('#strengthBar').style.background=colors[score];$('#strengthText').textContent=labels[score]}
function formatBytes(n){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(1)+' MB'}
function progress(n,stage){$('#progressBar').style.width=n+'%';$('#progressNumber').textContent=n+'%';$('#progressStage').textContent=stage;$('#progressTrack').setAttribute('aria-valuenow',n);if(n===100||/stopped|failed/i.test(stage))$('.status-panel').setAttribute('aria-busy','false')}
function setWorking(){els.error.textContent='';els.run.disabled=true;$('.status-panel').setAttribute('aria-busy','true');$('#statusChip').textContent='PROCESSING';$('#statusChip').style.background='#eee8ff';$('#statusTitle').textContent=operation==='encrypt'?'Building your vault…':'Verifying your vault…';$('#statusCopy').textContent='Key material exists only in this browser tab.';$('#orb').style.animationDuration='1s'}
function resetStatus(){progress(0,'Waiting for input');$('.status-panel').setAttribute('aria-busy','false');$('#statusChip').textContent='READY';$('#statusTitle').textContent='Vault standing by';$('#statusCopy').textContent='Select a file or enter text to begin. All processing stays within this tab.';$('#orb').style.animationDuration='4s'}
function resetResult(){els.result.classList.add('hidden');resultBlob=null;resultText='';resultFiles=[];$('#downloadResult').textContent='Download result ↓';resetStatus()}
function concat(...arrays){const out=new Uint8Array(arrays.reduce((n,a)=>n+a.length,0));let off=0;for(const a of arrays){out.set(a,off);off+=a.length}return out}
function u32(n){const a=new Uint8Array(4);new DataView(a.buffer).setUint32(0,n);return a}
async function derive(password,salt,iterations=ITERATIONS){const material=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
function makePlain(kind,name,data,entries){const meta=enc.encode(JSON.stringify({kind,name,date:new Date().toISOString(),entries}));return concat(u32(meta.length),meta,data)}
function readPlain(bytes){const len=new DataView(bytes.buffer,bytes.byteOffset,4).getUint32(0);if(len>bytes.length-4)throw Error('Invalid vault payload');const meta=JSON.parse(dec.decode(bytes.slice(4,4+len)));return{meta,data:bytes.slice(4+len)}}
async function encryptData(data,kind,name,entries){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));progress(12,'Generating salt + nonce');await tick();progress(28,'Hardening password');const key=await derive(els.password.value,salt);progress(68,'Encrypting with AES-256-GCM');const cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,tagLength:128},key,makePlain(kind,name,data,entries)));const header=enc.encode(JSON.stringify({v:1,brand:'Nivora Vault',alg:'AES-256-GCM',kdf:'PBKDF2-SHA-256',iter:ITERATIONS,salt:b64(salt),iv:b64(iv)}));progress(94,'Sealing authenticated container');await tick();return concat(MAGIC,u32(header.length),header,cipher)}
async function decryptData(container){if(container.length<29||!MAGIC.every((b,i)=>container[i]===b))throw Error('This is not a valid CipherSplat text package.');const hlen=new DataView(container.buffer,container.byteOffset+8,4).getUint32(0);if(hlen<2||hlen>4096||12+hlen+16>=container.length)throw Error('The vault header is invalid.');let h;try{h=JSON.parse(dec.decode(container.slice(12,12+hlen)))}catch{throw Error('The vault header is invalid.')}if(h.alg!=='AES-256-GCM'||h.kdf!=='PBKDF2-SHA-256'||!Number.isInteger(h.iter)||h.iter<100000||h.iter>2000000)throw Error('Unsupported or unsafe vault parameters.');const salt=fromB64(h.salt),iv=fromB64(h.iv);if(salt.length!==16||iv.length!==12)throw Error('Invalid package key parameters.');progress(20,'Reading vault parameters');const key=await derive(els.password.value,salt,h.iter);progress(62,'Verifying authentication tag');let plain;try{plain=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv,tagLength:128},key,container.slice(12+hlen)))}catch{throw Error('Unlock failed. The password is wrong or the data was altered.')}progress(90,'Restoring protected data');return readPlain(plain)}
function b64(bytes){let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}
function fromB64(s){if(typeof s!=='string'||!s.length||s.length%4===1||!/^[A-Za-z0-9+/]*={0,2}$/.test(s))throw Error('The encrypted text contains invalid Base64 data.');let raw;try{raw=atob(s)}catch{throw Error('The encrypted text contains invalid Base64 data.')}const out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
const tick=()=>new Promise(r=>setTimeout(r,180));
async function bundleEntries(){const chunks=[],meta=[];for(const entry of selectedEntries){const bytes=new Uint8Array(await entry.file.arrayBuffer());meta.push({path:entry.path.replace(/^\/+|\.\.(\/|\\)/g,''),size:bytes.length,type:entry.file.type});chunks.push(bytes)}return{data:concat(...chunks),meta}}
function unpackEntries(data,entries){let off=0;return entries.map(e=>{const bytes=data.slice(off,off+e.size);off+=e.size;return{path:e.path,blob:new Blob([bytes],{type:e.type||'application/octet-stream'})}})}
async function downloadResult(){if(resultFiles.length){if('showDirectoryPicker'in window){if(!confirm('Restore into a new or empty folder when possible. Existing files with matching names will be overwritten. Continue?'))return;let root;try{root=await window.showDirectoryPicker({mode:'readwrite'})}catch(e){if(e.name!=='AbortError')els.error.textContent='The destination folder could not be opened.';return}for(const item of resultFiles){if(!safePath(item.path))throw Error('Unsafe restoration path was blocked.');const parts=item.path.split('/');let dir=root;for(const part of parts.slice(0,-1))dir=await dir.getDirectoryHandle(part,{create:true});const handle=await dir.getFileHandle(parts.at(-1),{create:true}),writer=await handle.createWritable();try{await writer.write(item.blob);await writer.close()}catch(e){await writer.abort().catch(()=>{});throw e}}$('#downloadResult').textContent='Folder restored ✓'}else{if(!confirm(`Your browser will download ${resultFiles.length} files and flatten folder separators in their names. Continue?`))return;for(const item of resultFiles){const a=document.createElement('a');a.href=URL.createObjectURL(item.blob);a.download=item.path.replaceAll('/','__');a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}}return}const a=document.createElement('a');a.href=URL.createObjectURL(resultBlob);a.download=resultName;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function run(){if(!crypto.subtle){els.error.textContent='Web Crypto is unavailable. Open this page via HTTPS or localhost.';return}resetResult();setWorking();try{if(operation==='encrypt'){let data,kind,name,entries;if(mode==='file'){const bundle=await bundleEntries();data=bundle.data;entries=bundle.meta;kind=entries.length>1||entries[0].path.includes('/')?'folder':'file';name=kind==='folder'?entries[0].path.split('/')[0]:selectedEntries[0].file.name}else{data=enc.encode(els.text.value);kind='text';name='private-note.txt'}const output=await encryptData(data,kind,name,entries);resultName=(name||'vault')+'.prism';if(mode==='text'){resultText='PRISMVAULT1.'+b64(output);resultBlob=new Blob([resultText],{type:'text/plain'});resultName='encrypted-note.prism.txt'}else resultBlob=new Blob([output],{type:'application/octet-stream'});$('#resultTitle').textContent='Encryption complete';$('#resultMeta').textContent=`${formatBytes(resultBlob.size)} · ${entries?.length||1} item(s) · AES-256-GCM`;$('#copyResult').classList.toggle('hidden',mode!=='text')}else{const packed=mode==='file'?new Uint8Array(await selectedEntries[0].file.arrayBuffer()):fromB64(els.text.value.trim().replace(/^PRISMVAULT1\./,'')),unlocked=await decryptData(packed);resultName=unlocked.meta.name||'decrypted-data';if(unlocked.meta.kind==='folder'){resultFiles=unpackEntries(unlocked.data,unlocked.meta.entries);resultBlob=new Blob([]);$('#downloadResult').textContent='Restore folder ↓'}else{resultBlob=new Blob([unlocked.data],{type:unlocked.meta.entries?.[0]?.type||'application/octet-stream'});resultText=unlocked.meta.kind==='text'?dec.decode(unlocked.data):''}$('#resultTitle').textContent='Vault unlocked safely';$('#resultMeta').textContent=`${unlocked.meta.entries?.length||1} item(s) · authentication verified`;$('#copyResult').classList.toggle('hidden',!resultText);if(resultText)$('#copyResult').textContent='Copy decrypted text'}progress(100,'Complete — authentication verified');$('#statusChip').textContent='SECURED';$('#statusChip').style.background='#dff8ee';$('#statusTitle').textContent=operation==='encrypt'?'Vault sealed':'Vault authenticated';$('#statusCopy').textContent='The operation completed locally. Your key has not left this tab.';$('#orb').style.animationDuration='4s';els.result.classList.remove('hidden')}catch(e){els.error.textContent=e.message||String(e);$('#statusChip').textContent='STOPPED';$('#statusTitle').textContent='Vault operation failed';$('#statusCopy').textContent='No output was created. Check the input and password, then try again.';progress(0,'Operation stopped')}finally{sync()}}
const MAGIC2=enc.encode('NIVORA2!');
const CHUNK_SIZE=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)?1024*1024:4*1024*1024;
function ivFor(prefix,counter){const iv=new Uint8Array(12);iv.set(prefix);new DataView(iv.buffer).setUint32(8,counter);return iv}
const MAX_CHUNK_SIZE=8*1024*1024,MAX_META_SIZE=8*1024*1024,MAX_FILES=100000,MAX_RECORDS=0xffffffff;
function safePath(path){if(typeof path!=='string'||!path||path.length>4096||path.includes('\0'))return false;const parts=path.replace(/\\/g,'/').split('/');return parts.every(p=>p&&p!=='.'&&p!=='..'&&p.length<=255)}
function validateMetadata(meta,chunkSize){if(!meta||!['file','folder'].includes(meta.kind)||!Array.isArray(meta.files)||!meta.files.length||meta.files.length>MAX_FILES)throw Error('Invalid or excessive package metadata.');let records=1,total=0;for(const entry of meta.files){if(!entry||!safePath(entry.path)||!Number.isSafeInteger(entry.size)||entry.size<0||!Number.isSafeInteger(entry.chunks)||entry.chunks!==Math.ceil(entry.size/chunkSize))throw Error('Invalid file metadata in package.');records+=entry.chunks;total+=entry.size;if(!Number.isSafeInteger(total)||records>MAX_RECORDS)throw Error('Package exceeds safe processing limits.')}return meta}
async function sealRecord(key,prefix,counter,plain){if(!Number.isSafeInteger(counter)||counter<0||counter>MAX_RECORDS)throw Error('Package has too many encrypted records.');if(counter===0&&plain.length>MAX_META_SIZE)throw Error('This folder contains too much metadata for one safe package.');const aad=enc.encode(`NV2:${counter}`),cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv:ivFor(prefix,counter),additionalData:aad,tagLength:128},key,plain));return new Blob([u32(plain.length),u32(cipher.length),cipher])}
async function openRecord(file,offset,key,prefix,counter,maxPlain){if(!Number.isSafeInteger(offset)||offset<0||offset+8>file.size||counter>MAX_RECORDS)throw Error('The encrypted package ended unexpectedly.');const lens=new Uint8Array(await file.slice(offset,offset+8).arrayBuffer()),view=new DataView(lens.buffer),plainLen=view.getUint32(0),cipherLen=view.getUint32(4);if(cipherLen!==plainLen+16||plainLen>maxPlain||offset+8+cipherLen>file.size)throw Error('Invalid encrypted chunk length.');const cipher=await file.slice(offset+8,offset+8+cipherLen).arrayBuffer();let plain;try{plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:ivFor(prefix,counter),additionalData:enc.encode(`NV2:${counter}`),tagLength:128},key,cipher)}catch{throw Error('Unlock failed. The password is wrong or the package was altered.')}return{bytes:new Uint8Array(plain),next:offset+8+cipherLen}}
async function encryptFilesChunked(){const salt=crypto.getRandomValues(new Uint8Array(16)),prefix=crypto.getRandomValues(new Uint8Array(8));progress(8,'Generating package keys');const key=await derive(els.password.value,salt),total=selectedEntries.reduce((n,e)=>n+e.file.size,0);let counter=0,done=0;const files=selectedEntries.map(e=>({path:e.path.replace(/\\/g,'/').replace(/^\/+|(^|\/)\.\.(\/|$)/g,''),size:e.file.size,type:e.file.type,chunks:Math.ceil(e.file.size/CHUNK_SIZE)}));const name=files.length>1||files[0].path.includes('/')?files[0].path.split('/')[0]:files[0].path;const header=enc.encode(JSON.stringify({v:2,alg:'AES-256-GCM-CHUNKED',kdf:'PBKDF2-SHA-256',iter:ITERATIONS,salt:b64(salt),prefix:b64(prefix),chunkSize:CHUNK_SIZE}));const parts=[MAGIC2,u32(header.length),header];parts.push(await sealRecord(key,prefix,counter++,enc.encode(JSON.stringify({kind:files.length>1||files[0].path.includes('/')?'folder':'file',name,files}))));for(let f=0;f<selectedEntries.length;f++){const file=selectedEntries[f].file;for(let offset=0;offset<file.size;offset+=CHUNK_SIZE){const bytes=new Uint8Array(await file.slice(offset,Math.min(offset+CHUNK_SIZE,file.size)).arrayBuffer());parts.push(await sealRecord(key,prefix,counter++,bytes));done+=bytes.length;progress(30+Math.round(64*done/Math.max(total,1)),`Encrypting ${f+1} of ${files.length} · ${formatBytes(done)}`);await new Promise(requestAnimationFrame)}}progress(98,'Finalizing chunked package');return{blob:new Blob(parts,{type:'application/octet-stream'}),name:name+'.nivora',count:files.length}}
async function decryptFilesChunked(file){if(file.size<29)throw Error('This package is too short to be valid.');const prefixBytes=new Uint8Array(await file.slice(0,12).arrayBuffer());if(!MAGIC2.every((b,i)=>prefixBytes[i]===b))throw Error('This is not a CipherSplat v2 package.');const hlen=new DataView(prefixBytes.buffer).getUint32(8);if(hlen<2||hlen>4096||12+hlen+24>file.size)throw Error('Invalid package header.');let h;try{h=JSON.parse(dec.decode(await file.slice(12,12+hlen).arrayBuffer()))}catch{throw Error('Invalid package header encoding.')}if(h.alg!=='AES-256-GCM-CHUNKED'||h.kdf!=='PBKDF2-SHA-256'||!Number.isInteger(h.iter)||h.iter<100000||h.iter>2000000||!Number.isInteger(h.chunkSize)||h.chunkSize<65536||h.chunkSize>MAX_CHUNK_SIZE)throw Error('Unsupported or unsafe package parameters.');const salt=fromB64(h.salt),prefix=fromB64(h.prefix);if(salt.length!==16||prefix.length!==8)throw Error('Invalid package key parameters.');progress(12,'Hardening password');const key=await derive(els.password.value,salt,h.iter);let offset=12+hlen,counter=0;const metaRecord=await openRecord(file,offset,key,prefix,counter++,MAX_META_SIZE);offset=metaRecord.next;let meta;try{meta=validateMetadata(JSON.parse(dec.decode(metaRecord.bytes)),h.chunkSize)}catch(e){throw Error(e.message==='Invalid or excessive package metadata.'||e.message==='Invalid file metadata in package.'||e.message==='Package exceeds safe processing limits.'?e.message:'Invalid encrypted metadata.')}const files=[];let completed=0;for(const entry of meta.files){const parts=[];let restored=0;for(let c=0;c<entry.chunks;c++){const record=await openRecord(file,offset,key,prefix,counter++,h.chunkSize);offset=record.next;parts.push(record.bytes);restored+=record.bytes.length;completed+=record.bytes.length;progress(25+Math.round(70*offset/file.size),`Authenticating ${formatBytes(completed)}`);await new Promise(requestAnimationFrame)}if(restored!==entry.size)throw Error('Authenticated file size does not match package metadata.');files.push({path:entry.path,blob:new Blob(parts,{type:typeof entry.type==='string'?entry.type.slice(0,255):'application/octet-stream'})})}if(offset!==file.size)throw Error('The package contains unexpected trailing data.');return{meta,files}}
async function runLarge(){if(mode==='text')return run();if(!crypto.subtle){els.error.textContent='Web Crypto is unavailable. Use HTTPS or localhost.';return}resetResult();setWorking();try{if(operation==='encrypt'){const packed=await encryptFilesChunked();resultBlob=packed.blob;resultName=packed.name.replace(/\.nivora$/,'.ciphersplat');$('#resultTitle').textContent='Encryption complete';$('#resultMeta').textContent=`${formatBytes(resultBlob.size)} · ${packed.count} item(s) · chunk-authenticated`;$('#copyResult').classList.add('hidden')}else{const first=new Uint8Array(await selectedEntries[0].file.slice(0,8).arrayBuffer());if(!MAGIC2.every((b,i)=>first[i]===b))return run();const unlocked=await decryptFilesChunked(selectedEntries[0].file);if(unlocked.meta.kind==='folder'){resultFiles=unlocked.files;resultBlob=new Blob([]);$('#downloadResult').textContent='Restore folder ↓'}else{resultBlob=unlocked.files[0].blob;resultName=unlocked.files[0].path}$('#resultTitle').textContent='Vault unlocked safely';$('#resultMeta').textContent=`${unlocked.files.length} item(s) · every chunk authenticated`;$('#copyResult').classList.add('hidden')}progress(100,'Complete — authentication verified');$('#statusChip').textContent='SECURED';$('#statusChip').style.background='#dff8ee';$('#statusTitle').textContent=operation==='encrypt'?'Vault sealed':'Vault authenticated';$('#statusCopy').textContent='Processed in bounded chunks. No data left this device.';$('#orb').style.animationDuration='4s';els.result.classList.remove('hidden')}catch(e){els.error.textContent=e.message||String(e);$('#statusChip').textContent='STOPPED';$('#statusTitle').textContent='Vault operation failed';$('#statusCopy').textContent='No output was created. Check the input and password.';progress(0,'Operation stopped')}finally{sync()}}
const encryptFilesChunkedUnchecked=encryptFilesChunked;
encryptFilesChunked=async function(){if(!selectedEntries.length||selectedEntries.length>MAX_FILES)throw Error('Select between 1 and 100,000 files per package.');let records=1;for(const entry of selectedEntries){const normalized=entry.path.replace(/\\/g,'/');if(!safePath(normalized))throw Error(`Unsafe or unsupported filename: ${entry.file.name}`);records+=Math.ceil(entry.file.size/CHUNK_SIZE);if(records>MAX_RECORDS)throw Error('The selection contains too many chunks for one package.')}return encryptFilesChunkedUnchecked()};
new MutationObserver(()=>{if(!els.result.classList.contains('hidden')){els.password.value='';els.password.type='password';updateStrength();sync();requestAnimationFrame(()=>els.result.focus())}}).observe(els.result,{attributes:true,attributeFilter:['class']});
sync();
