const $ = (id) => document.getElementById(id);
const STORAGE_KEY = "qrsplat.designs.v1";
const CONFIG_KEY = "qrsplat.backend.v1";
const state = { mode:"standard", editAction:"create", svg:"", payload:"", adminKey:"", logoData:"", originalLogoData:"", templateLogoData:"" };
const templates = {
  classic:{dark:"#172033",light:"#ffffff"},
  drawsplat:{dark:"#6d38e8",light:"#ffffff"},
  custom:null,
};

function escapeXml(value){return String(value).replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"})[char]);}
function escapeWifi(value){return value.replace(/([\\;,:"])/g,"\\$1");}
function payload(){
  const type=$("contentType").value;
  if(type==="wifi") return `WIFI:T:${$("wifiSecurity").value};S:${escapeWifi($("wifiName").value)};P:${escapeWifi($("wifiPassword").value)};H:${$("wifiHidden").checked};`; 
  const value=$("qrContent").value.trim();
  if(type==="email") return value.startsWith("mailto:")?value:`mailto:${value}`;
  if(type==="phone") return value.startsWith("tel:")?value:`tel:${value}`;
  return value;
}
function finderCell(row,col,count){return (row<7&&col<7)||(row<7&&col>=count-7)||(row>=count-7&&col<7);}
function makeSvg(value){
  if(!value) return "";
  const qr=qrcode(0,$("errorLevel").value); qr.addData(value); qr.make();
  const count=qr.getModuleCount(),quiet=Number($("quietZone").value),total=count+quiet*2,dark=$("darkColor").value,light=$("lightColor").value;
  let cells=""; for(let row=0;row<count;row++)for(let col=0;col<count;col++)if(qr.isDark(row,col))cells+=`<rect x="${col+quiet}" y="${row+quiet}" width="1" height="1"${finderCell(row,col,count)?' class="finder"':""}/>`;
  const activeLogo=state.logoData||($("template").value==="drawsplat"?state.templateLogoData:"");
  const logoSize=total*Number($("centerImageSize").value)/100,logoX=(total-logoSize)/2,pad=Math.max(.8,logoSize*.08);
  const logo=activeLogo?`<rect x="${logoX-pad}" y="${logoX-pad}" width="${logoSize+pad*2}" height="${logoSize+pad*2}" rx="${pad}" fill="${light}"/><image href="${escapeXml(activeLogo)}" x="${logoX}" y="${logoX}" width="${logoSize}" height="${logoSize}" preserveAspectRatio="xMidYMid meet"/>`:"";
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${total} ${total}" width="${$("qrSize").value}" height="${$("qrSize").value}" role="img" aria-label="QR code"><rect width="${total}" height="${total}" fill="${light}"/><g fill="${dark}">${cells}</g>${logo}</svg>`;
}
function render(){
  try{state.payload=state.mode==="editable"?(state.shortUrl||$("editableDestination").value.trim()):payload();state.svg=makeSvg(state.payload);$("qrPreview").innerHTML=state.svg||'<p>Enter content to create a QR code.</p>';$("payloadPreview").textContent=state.payload||"Nothing yet";$("scanMessage").textContent=state.svg?"Ready to scan":"Add content to continue";}catch(error){state.svg="";$("qrPreview").innerHTML="<p>This content is too long for the selected error-correction level.</p>";$("scanMessage").textContent=error.message;}}
function setContentType(){const type=$("contentType").value,wifi=type==="wifi";$("wifiFields").hidden=!wifi;$("primaryField").hidden=wifi;const labels={url:["Destination URL","url","https://example.org/resource"],text:["Text","text","Type or paste text"],email:["Email address","email","name@example.org"],phone:["Phone number","tel","+1 555 555 5555"]};if(!wifi){const [label,typeValue,placeholder]=labels[type];$("primaryField").childNodes[0].nodeValue=label;$("qrContent").type=typeValue;$("qrContent").placeholder=placeholder;}render();}
function setMode(mode){state.mode=mode;document.querySelectorAll("[data-mode]").forEach(button=>{const active=button.dataset.mode===mode;button.classList.toggle("active",active);button.setAttribute("aria-pressed",active)});$("standardFields").hidden=mode!=="standard";$("editableFields").hidden=mode!=="editable";state.shortUrl="";updateBackendState();render();}
function config(){try{return JSON.parse(localStorage.getItem(CONFIG_KEY))||{};}catch{return {};}}
function updateBackendState(){const ready=Boolean(config().endpoint&&config().redirectBase);$("editableRun").disabled=!ready;$("editableStatus").textContent=ready?"Editable QR service configured in this browser.":"An administrator must configure the editable QR service first.";}
function setEditAction(action){state.editAction=action;document.querySelectorAll("[data-edit-action]").forEach(button=>button.classList.toggle("active",button.dataset.editAction===action));$("codeField").hidden=action!=="update";$("editableRun").textContent=action==="create"?"Create editable QR":"Update destination";}
async function runEditable(){const settings=config(),destination=$("editableDestination").value.trim();if(!settings.endpoint||!destination){$("editableStatus").textContent="Add a valid destination and configure the service.";return;}const code=$("editableCode").value.trim();if(state.editAction==="update"&&!code){$("editableStatus").textContent="Enter the existing QR code ID.";return;}$("editableRun").disabled=true;$("editableStatus").textContent="Contacting the configured redirect service…";try{const response=await fetch(settings.endpoint,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action:state.editAction,destination,code,adminKey:state.adminKey})});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||"The service rejected this request.");const resultCode=result.code||code;state.shortUrl=result.shortUrl||`${settings.redirectBase}${encodeURIComponent(resultCode)}`;$("editableCode").value=resultCode;$("editableStatus").textContent=state.editAction==="create"?`Editable QR created. Save the code ID: ${resultCode}`:"Destination updated. The existing QR image remains valid.";render();}catch(error){$("editableStatus").textContent=`Editable QR service error: ${error.message}`;}finally{$("editableRun").disabled=false;}}
function designs(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||[];}catch{return [];}}
function refreshDesigns(){const select=$("savedDesigns"),value=select.value;select.innerHTML='<option value="">Choose a saved design…</option>';for(const design of designs()){const option=document.createElement("option");option.value=design.id;option.textContent=design.name;select.append(option)}select.value=value;}
function snapshot(){return{id:crypto.randomUUID(),name:$("designName").value.trim()||"Untitled QR",contentType:$("contentType").value,content:$("qrContent").value,wifiName:$("wifiName").value,wifiPassword:"",wifiSecurity:$("wifiSecurity").value,wifiHidden:$("wifiHidden").checked,template:$("template").value,dark:$("darkColor").value,light:$("lightColor").value,size:$("qrSize").value,error:$("errorLevel").value,quiet:$("quietZone").value};}
function saveDesign(){const list=designs(),item=snapshot(),existing=list.findIndex(entry=>entry.name===item.name);if(existing>=0)item.id=list[existing].id, list.splice(existing,1,item);else list.unshift(item);localStorage.setItem(STORAGE_KEY,JSON.stringify(list.slice(0,30)));refreshDesigns();$("savedDesigns").value=item.id;$("scanMessage").textContent="Design saved only in this browser.";}
function loadDesign(id){const item=designs().find(entry=>entry.id===id);if(!item)return;$("designName").value=item.name;$("contentType").value=item.contentType;$("qrContent").value=item.content;$("wifiName").value=item.wifiName;$("wifiPassword").value=item.wifiPassword;$("wifiSecurity").value=item.wifiSecurity;$("wifiHidden").checked=item.wifiHidden;$("template").value=templates[item.template]||item.template==="custom"?item.template:"classic";$("darkColor").value=item.dark;$("lightColor").value=item.light;$("qrSize").value=item.size;$("errorLevel").value=item.error;$("quietZone").value=item.quiet;setContentType();updateQuiet();render();}
function applyTemplate(){const item=templates[$("template").value];if(item){$("darkColor").value=item.dark;$("lightColor").value=item.light;if($("template").value==="drawsplat")$("errorLevel").value="H";}render();}
function updateQuiet(){$("quietOutput").textContent=`${$("quietZone").value} modules`;render();}
function updateCenterImageSize(){$("centerImageSizeOutput").textContent=`${$("centerImageSize").value}% of QR width`;render();}
function removeCenterImage(){state.logoData="";state.originalLogoData="";$("centerImage").value="";$("cartoonEffect").checked=false;$("centerImageControls").hidden=true;$("centerImageHelp").textContent="PNG, JPEG, or WebP, up to 2 MB. The image stays on this device. Test the finished QR before sharing.";render();}
async function cartoonize(dataUrl){const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=dataUrl});const scale=Math.min(1,512/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const context=canvas.getContext("2d");context.drawImage(image,0,0,canvas.width,canvas.height);const pixels=context.getImageData(0,0,canvas.width,canvas.height),source=new Uint8ClampedArray(pixels.data),step=51;for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){const i=(y*canvas.width+x)*4;if(source[i+3]===0)continue;const right=(y*canvas.width+Math.min(x+1,canvas.width-1))*4,down=(Math.min(y+1,canvas.height-1)*canvas.width+x)*4,light=(source[i]+source[i+1]+source[i+2])/3,rightLight=(source[right]+source[right+1]+source[right+2])/3,downLight=(source[down]+source[down+1]+source[down+2])/3,edge=Math.max(Math.abs(light-rightLight),Math.abs(light-downLight))>38;if(edge){pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=25;}else{pixels.data[i]=Math.round(source[i]/step)*step;pixels.data[i+1]=Math.round(source[i+1]/step)*step;pixels.data[i+2]=Math.round(source[i+2]/step)*step;}}context.putImageData(pixels,0,0);return canvas.toDataURL("image/png");}
async function updateLogoEffect(){$("centerImageHelp").textContent="Applying the local cartoon effect…";try{state.logoData=$("cartoonEffect").checked?await cartoonize(state.originalLogoData):state.originalLogoData;$("centerImageHelp").textContent=$("cartoonEffect").checked?"Cartoon effect applied locally. High error correction is enabled; test the finished QR.":"Original center image restored. High error correction is enabled; test the finished QR.";render();}catch{$("centerImageHelp").textContent="The cartoon effect could not be applied to this image.";}}
function loadCenterImage(){const file=$("centerImage").files[0],allowed=new Set(["image/png","image/jpeg","image/webp"]);if(!file)return removeCenterImage();if(!allowed.has(file.type)||file.size>2*1024*1024){$("centerImage").value="";$("centerImageHelp").textContent="Choose a PNG, JPEG, or WebP image no larger than 2 MB.";return;}const reader=new FileReader();reader.onload=()=>{state.originalLogoData=reader.result;state.logoData=reader.result;$("cartoonEffect").checked=false;$("errorLevel").value="H";$("centerImageControls").hidden=false;$("centerImageHelp").textContent=`${file.name} added locally. High error correction enabled; test the finished QR before sharing.`;render();};reader.onerror=()=>{$("centerImageHelp").textContent="That image could not be read. Try another file.";};reader.readAsDataURL(file);}
async function loadTemplateLogo(){try{const response=await fetch("../../assets/brand/DrawSplat_logo_transparent.png");if(!response.ok)return;const blob=await response.blob(),reader=new FileReader();state.templateLogoData=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)});render();}catch{state.templateLogoData="";}}
function fileName(ext){return `${($("designName").value||"qrsplat").trim().replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toLowerCase()||"qrsplat"}.${ext}`;}
function download(blob,name){const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function canvasBlob(){const size=Number($("qrSize").value),canvas=$("renderCanvas"),context=canvas.getContext("2d"),image=new Image();canvas.width=canvas.height=size;const svgBlob=new Blob([state.svg],{type:"image/svg+xml"}),url=URL.createObjectURL(svgBlob);await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=url});context.clearRect(0,0,size,size);context.drawImage(image,0,0,size,size);URL.revokeObjectURL(url);return new Promise(resolve=>canvas.toBlob(resolve,"image/png"));}
async function copyPng(){if(!state.svg)return;try{const blob=await canvasBlob();await navigator.clipboard.write([new ClipboardItem({"image/png":blob})]);$("scanMessage").textContent="PNG copied to clipboard.";}catch{$("scanMessage").textContent="This browser blocked image copying. Use Download PNG instead.";}}
async function copySvg(){if(!state.svg)return;try{await navigator.clipboard.writeText(state.svg);$("scanMessage").textContent="SVG markup copied to clipboard.";}catch{$("scanMessage").textContent="Clipboard access was blocked. Use Download SVG instead.";}}

document.querySelectorAll("[data-mode]").forEach(button=>button.onclick=()=>setMode(button.dataset.mode));document.querySelectorAll("[data-edit-action]").forEach(button=>button.onclick=()=>setEditAction(button.dataset.editAction));
$("contentType").onchange=setContentType;for(const input of document.querySelectorAll("#qrForm input,#qrForm select"))input.addEventListener("input",render);$("template").onchange=applyTemplate;$("quietZone").oninput=updateQuiet;$("centerImage").onchange=loadCenterImage;$("centerImageSize").oninput=updateCenterImageSize;$("cartoonEffect").onchange=updateLogoEffect;$("removeCenterImage").onclick=removeCenterImage;$("saveDesign").onclick=saveDesign;$("savedDesigns").onchange=()=>loadDesign($("savedDesigns").value);$("newDesign").onclick=()=>location.reload();$("copyPng").onclick=copyPng;$("copySvg").onclick=copySvg;$("downloadSvg").onclick=()=>state.svg&&download(new Blob([state.svg],{type:"image/svg+xml"}),fileName("svg"));$("downloadPng").onclick=async()=>state.svg&&download(await canvasBlob(),fileName("png"));$("backendSetup").onclick=()=>{const item=config();$("backendUrl").value=item.endpoint||"";$("redirectBase").value=item.redirectBase||"";$("adminKey").value="";$("backendDialog").showModal()};$("saveBackend").onclick=(event)=>{event.preventDefault();const endpoint=$("backendUrl").value.trim(),redirectBase=$("redirectBase").value.trim();if(!endpoint||!redirectBase)return;localStorage.setItem(CONFIG_KEY,JSON.stringify({endpoint,redirectBase}));state.adminKey=$("adminKey").value;$("backendDialog").close();updateBackendState()};$("editableRun").onclick=runEditable;
setContentType();refreshDesigns();updateBackendState();updateQuiet();updateCenterImageSize();loadTemplateLogo();render();
