const $ = (id) => document.getElementById(id);
const STORAGE_KEY = "qrsplat.designs.v1";
const CONFIG_KEY = "qrsplat.backend.v1";
const state = { mode:"standard", editAction:"create", svg:"", payload:"", adminKey:"", logoData:"" };
const templates = {
  classic:{dark:"#172033",light:"#ffffff",mark:false},
  drawsplat:{dark:"#6d38e8",light:"#ffffff",mark:true},
  tcea:{dark:"#00558c",light:"#ffffff",mark:false},
  custom:null,
};

function escapeXml(value){return String(value).replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"})[char]);}
function escapeWifi(value){return value.replace(/([\\;,:"])/g,"\\$1");}
function payload(){
  const type=$("contentType").value;
  if(type==="wifi") return `WIFI:T:${$("wifiSecurity").value};S:${escapeWifi($("wifiName").value)};P:${escapeWifi($("wifiPassword").value)};H:${$("wifiHidden").checked};`; 
  const value=$("qrContent").value.trim();
  if(type==="email") return value.startsWith("mailto:")?value:`mailto:${value}`;
  if(type==="phone") return value.startsWith("tel:")?value:`tel:${value}`;
  return value;
}
function finderCell(row,col,count){return (row<7&&col<7)||(row<7&&col>=count-7)||(row>=count-7&&col<7);}
function makeSvg(value){
  if(!value) return "";
  const qr=qrcode(0,$("errorLevel").value); qr.addData(value); qr.make();
  const count=qr.getModuleCount(),quiet=Number($("quietZone").value),total=count+quiet*2,dark=$("darkColor").value,light=$("lightColor").value;
  let cells=""; for(let row=0;row<count;row++)for(let col=0;col<count;col++)if(qr.isDark(row,col))cells+=`<rect x="${col+quiet}" y="${row+quiet}" width="1" height="1"${finderCell(row,col,count)?' class="finder"':""}/>`;
  const mark=$("brandMark").checked?`<rect x="${total/2-5.5}" y="${total/2-5.5}" width="11" height="11" rx="2" fill="${light}"/><circle cx="${total/2}" cy="${total/2}" r="4.2" fill="${dark}"/><path d="M${total/2} ${total/2-2.8}l.9 1.8 2 .3-1.45 1.4.35 2-1.8-.95-1.8.95.35-2-1.45-1.4 2-.3z" fill="${light}"/>`:"";
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${total} ${total}" width="${$("qrSize").value}" height="${$("qrSize").value}" role="img" aria-label="QR code"><rect width="${total}" height="${total}" fill="${light}"/><g fill="${dark}">${cells}</g>${mark}</svg>`;
}
function render(){
  try{state.payload=state.mode==="editable"?(state.shortUrl||$("editableDestination").value.trim()):payload();state.svg=makeSvg(state.payload);$("qrPreview").innerHTML=state.svg||'<p>Enter content to create a QR code.</p>';$("payloadPreview").textContent=state.payload||"Nothing yet";$("scanMessage").textContent=state.svg?"Ready to scan":"Add content to continue";}catch(error){state.svg="";$("qrPreview").innerHTML="<p>This content is too long for the selected error-correction level.</p>";$("scanMessage").textContent=error.message;}}
function setContentType(){const type=$("contentType").value,wifi=type==="wifi";$("wifiFields").hidden=!wifi;$("primaryField").hidden=wifi;const labels={url:["Destination URL","url","https://example.org/resource"],text:["Text","text","Type or paste text"],email:["Email address","email","name@example.org"],phone:["Phone number","tel","+1 555 555 5555"]};if(!wifi){const [label,typeValue,placeholder]=labels[type];$("primaryField").childNodes[0].nodeValue=label;$("qrContent").type=typeValue;$("qrContent").placeholder=placeholder;}render();}
function setMode(mode){state.mode=mode;document.querySelectorAll("[data-mode]").forEach(button=>{const active=button.dataset.mode===mode;button.classList.toggle("active",active);button.setAttribute("aria-pressed",active)});$("standardFields").hidden=mode!=="standard";$("editableFields").hidden=mode!=="editable";state.shortUrl="";updateBackendState();render();}
function config(){try{return JSON.parse(localStorage.getItem(CONFIG_KEY))||{};}catch{return {};}}
function updateBackendState(){const ready=Boolean(config().endpoint&&config().redirectBase);$("editableRun").disabled=!ready;$("editableStatus").textContent=ready?"Editable QR service configured in this browser.":"An administrator must configure the editable QR service first.";}
function setEditAction(action){state.editAction=action;document.querySelectorAll("[data-edit-action]").forEach(button=>button.classList.toggle("active",button.dataset.editAction===action));$("codeField").hidden=action!=="update";$("editableRun").textContent=action==="create"?"Create editable QR":"Update destination";}
async function runEditable(){const settings=config(),destination=$("editableDestination").value.trim();if(!settings.endpoint||!destination){$("editableStatus").textContent="Add a valid destination and configure the service.";return;}const code=$("editableCode").value.trim();if(state.editAction==="update"&&!code){$("editableStatus").textContent="Enter the existing QR code ID.";return;}$("editableRun").disabled=true;$("editableStatus").textContent="Contacting the configured redirect service…";try{const response=await fetch(settings.endpoint,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action:state.editAction,destination,code,adminKey:state.adminKey})});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||"The service rejected this request.");const resultCode=result.code||code;state.shortUrl=result.shortUrl||`${settings.redirectBase}${encodeURIComponent(resultCode)}`;$("editableCode").value=resultCode;$("editableStatus").textContent=state.editAction==="create"?`Editable QR created. Save the code ID: ${resultCode}`:"Destination updated. The existing QR image remains valid.";render();}catch(error){$("editableStatus").textContent=`Editable QR service error: ${error.message}`;}finally{$("editableRun").disabled=false;}}
function designs(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||[];}catch{return [];}}
function refreshDesigns(){const select=$("savedDesigns"),value=select.value;select.innerHTML='<option value="">Choose a saved design…</option>';for(const design of designs()){const option=document.createElement("option");option.value=design.id;option.textContent=design.name;select.append(option)}select.value=value;}
function snapshot(){return{id:crypto.randomUUID(),name:$("designName").value.trim()||"Untitled QR",contentType:$("contentType").value,content:$("qrContent").value,wifiName:$("wifiName").value,wifiPassword:"",wifiSecurity:$("wifiSecurity").value,wifiHidden:$("wifiHidden").checked,template:$("template").value,dark:$("darkColor").value,light:$("lightColor").value,size:$("qrSize").value,error:$("errorLevel").value,quiet:$("quietZone").value,mark:$("brandMark").checked};}
function saveDesign(){const list=designs(),item=snapshot(),existing=list.findIndex(entry=>entry.name===item.name);if(existing>=0)item.id=list[existing].id, list.splice(existing,1,item);else list.unshift(item);localStorage.setItem(STORAGE_KEY,JSON.stringify(list.slice(0,30)));refreshDesigns();$("savedDesigns").value=item.id;$("scanMessage").textContent="Design saved only in this browser.";}
function loadDesign(id){const item=designs().find(entry=>entry.id===id);if(!item)return;$("designName").value=item.name;$("contentType").value=item.contentType;$("qrContent").value=item.content;$("wifiName").value=item.wifiName;$("wifiPassword").value=item.wifiPassword;$("wifiSecurity").value=item.wifiSecurity;$("wifiHidden").checked=item.wifiHidden;$("template").value=item.template;$("darkColor").value=item.dark;$("lightColor").value=item.light;$("qrSize").value=item.size;$("errorLevel").value=item.error;$("quietZone").value=item.quiet;$("brandMark").checked=item.mark;setContentType();updateQuiet();render();}
function applyTemplate(){const item=templates[$("template").value];if(item){$("darkColor").value=item.dark;$("lightColor").value=item.light;$("brandMark").checked=item.mark;if(item.mark)$("errorLevel").value="H";}render();}
function updateQuiet(){$("quietOutput").textContent=`${$("quietZone").value} modules`;render();}
function fileName(ext){return `${($("designName").value||"qrsplat").trim().replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toLowerCase()||"qrsplat"}.${ext}`;}
function download(blob,name){const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function canvasBlob(){const size=Number($("qrSize").value),canvas=$("renderCanvas"),context=canvas.getContext("2d"),image=new Image();canvas.width=canvas.height=size;const svgBlob=new Blob([state.svg],{type:"image/svg+xml"}),url=URL.createObjectURL(svgBlob);await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=url});context.clearRect(0,0,size,size);context.drawImage(image,0,0,size,size);URL.revokeObjectURL(url);return new Promise(resolve=>canvas.toBlob(resolve,"image/png"));}
async function copyPng(){if(!state.svg)return;try{const blob=await canvasBlob();await navigator.clipboard.write([new ClipboardItem({"image/png":blob})]);$("scanMessage").textContent="PNG copied to clipboard.";}catch{$("scanMessage").textContent="This browser blocked image copying. Use Download PNG instead.";}}
async function copySvg(){if(!state.svg)return;try{await navigator.clipboard.writeText(state.svg);$("scanMessage").textContent="SVG markup copied to clipboard.";}catch{$("scanMessage").textContent="Clipboard access was blocked. Use Download SVG instead.";}}

document.querySelectorAll("[data-mode]").forEach(button=>button.onclick=()=>setMode(button.dataset.mode));document.querySelectorAll("[data-edit-action]").forEach(button=>button.onclick=()=>setEditAction(button.dataset.editAction));
$("contentType").onchange=setContentType;for(const input of document.querySelectorAll("#qrForm input,#qrForm select"))input.addEventListener("input",render);$("template").onchange=applyTemplate;$("quietZone").oninput=updateQuiet;$("saveDesign").onclick=saveDesign;$("savedDesigns").onchange=()=>loadDesign($("savedDesigns").value);$("newDesign").onclick=()=>location.reload();$("copyPng").onclick=copyPng;$("copySvg").onclick=copySvg;$("downloadSvg").onclick=()=>state.svg&&download(new Blob([state.svg],{type:"image/svg+xml"}),fileName("svg"));$("downloadPng").onclick=async()=>state.svg&&download(await canvasBlob(),fileName("png"));$("backendSetup").onclick=()=>{const item=config();$("backendUrl").value=item.endpoint||"";$("redirectBase").value=item.redirectBase||"";$("adminKey").value="";$("backendDialog").showModal()};$("saveBackend").onclick=(event)=>{event.preventDefault();const endpoint=$("backendUrl").value.trim(),redirectBase=$("redirectBase").value.trim();if(!endpoint||!redirectBase)return;localStorage.setItem(CONFIG_KEY,JSON.stringify({endpoint,redirectBase}));state.adminKey=$("adminKey").value;$("backendDialog").close();updateBackendState()};$("editableRun").onclick=runEditable;
setContentType();refreshDesigns();updateBackendState();updateQuiet();render();
